/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1ProjectsUpdate } from "../../funcs/mcpApiV1ProjectsUpdate.js";
import { ApiV1ProjectsUpdateRequest$zodSchema } from "../../models/apiv1projectsupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1ProjectsUpdateRequest$zodSchema,
};

export const tool$mcpApiV1ProjectsUpdate: ToolDefinition<typeof args> = {
  name: "mcp-api-v1-projects-update",
  description: ``,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await mcpApiV1ProjectsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
