/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1ProjectsFeaturesMvOptionsUpdate } from "../../funcs/mcpApiV1ProjectsFeaturesMvOptionsUpdate.js";
import { ApiV1ProjectsFeaturesMvOptionsUpdateRequest$zodSchema } from "../../models/apiv1projectsfeaturesmvoptionsupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1ProjectsFeaturesMvOptionsUpdateRequest$zodSchema,
};

export const tool$mcpApiV1ProjectsFeaturesMvOptionsUpdate: ToolDefinition<
  typeof args
> = {
  name: "mcp-api-v1-projects-features-mv-options-update",
  description: ``,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await mcpApiV1ProjectsFeaturesMvOptionsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
