/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1OrganisationsGroupsList } from "../../funcs/mcpApiV1OrganisationsGroupsList.js";
import { ApiV1OrganisationsGroupsListRequest$zodSchema } from "../../models/apiv1organisationsgroupslistop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1OrganisationsGroupsListRequest$zodSchema,
};

export const tool$mcpApiV1OrganisationsGroupsList: ToolDefinition<typeof args> =
  {
    name: "mcp-api-v1-organisations-groups-list",
    description: ``,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await mcpApiV1OrganisationsGroupsList(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
