/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1EnvironmentsListChangeRequestsRetrieve } from "../../funcs/mcpApiV1EnvironmentsListChangeRequestsRetrieve.js";
import { ApiV1EnvironmentsListChangeRequestsRetrieveRequest$zodSchema } from "../../models/apiv1environmentslistchangerequestsretrieveop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1EnvironmentsListChangeRequestsRetrieveRequest$zodSchema,
};

export const tool$mcpApiV1EnvironmentsListChangeRequestsRetrieve:
  ToolDefinition<typeof args> = {
    name: "mcp-api-v1-environments-list-change-requests-285",
    description: ``,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await mcpApiV1EnvironmentsListChangeRequestsRetrieve(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
