/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1ProjectsEnvironmentsRetrieve } from "../../funcs/mcpApiV1ProjectsEnvironmentsRetrieve.js";
import { ApiV1ProjectsEnvironmentsRetrieveRequest$zodSchema } from "../../models/apiv1projectsenvironmentsretrieveop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1ProjectsEnvironmentsRetrieveRequest$zodSchema,
};

export const tool$mcpApiV1ProjectsEnvironmentsRetrieve: ToolDefinition<
  typeof args
> = {
  name: "mcp-api-v1-projects-environments-retrieve",
  description: ``,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await mcpApiV1ProjectsEnvironmentsRetrieve(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
