/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1ProjectsFeaturesMvOptionsDestroy } from "../../funcs/mcpApiV1ProjectsFeaturesMvOptionsDestroy.js";
import { ApiV1ProjectsFeaturesMvOptionsDestroyRequest$zodSchema } from "../../models/apiv1projectsfeaturesmvoptionsdestroyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1ProjectsFeaturesMvOptionsDestroyRequest$zodSchema,
};

export const tool$mcpApiV1ProjectsFeaturesMvOptionsDestroy: ToolDefinition<
  typeof args
> = {
  name: "mcp-api-v1-projects-features-mv-options-destroy",
  description: ``,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await mcpApiV1ProjectsFeaturesMvOptionsDestroy(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
