/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1ProjectsFeaturesFeatureExternalResourcesList } from "../../funcs/mcpApiV1ProjectsFeaturesFeatureExternalResourcesList.js";
import { ApiV1ProjectsFeaturesFeatureExternalResourcesListRequest$zodSchema } from "../../models/apiv1projectsfeaturesfeatureexternalresourceslistop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1ProjectsFeaturesFeatureExternalResourcesListRequest$zodSchema,
};

export const tool$mcpApiV1ProjectsFeaturesFeatureExternalResourcesList:
  ToolDefinition<typeof args> = {
    name: "mcp-api-v1-projects-features-feature-external-1f7",
    description: ``,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await mcpApiV1ProjectsFeaturesFeatureExternalResourcesList(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
