/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1EnvironmentsFeaturesVersionsList } from "../../funcs/mcpApiV1EnvironmentsFeaturesVersionsList.js";
import { ApiV1EnvironmentsFeaturesVersionsListRequest$zodSchema } from "../../models/apiv1environmentsfeaturesversionslistop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1EnvironmentsFeaturesVersionsListRequest$zodSchema,
};

export const tool$mcpApiV1EnvironmentsFeaturesVersionsList: ToolDefinition<
  typeof args
> = {
  name: "mcp-api-v1-environments-features-versions-list",
  description: ``,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await mcpApiV1EnvironmentsFeaturesVersionsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
