/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesCreate } from "../../funcs/mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesCreate.js";
import { ApiV1EnvironmentsFeaturesVersionsFeaturestatesCreateRequest$zodSchema } from "../../models/apiv1environmentsfeaturesversionsfeaturestatescreateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    ApiV1EnvironmentsFeaturesVersionsFeaturestatesCreateRequest$zodSchema,
};

export const tool$mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesCreate:
  ToolDefinition<typeof args> = {
    name: "mcp-api-v1-environments-features-versions-e40",
    description: ``,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesCreate(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
