/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1ProjectsSegmentsCreate } from "../../funcs/mcpApiV1ProjectsSegmentsCreate.js";
import { ApiV1ProjectsSegmentsCreateRequest$zodSchema } from "../../models/apiv1projectssegmentscreateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1ProjectsSegmentsCreateRequest$zodSchema,
};

export const tool$mcpApiV1ProjectsSegmentsCreate: ToolDefinition<typeof args> =
  {
    name: "mcp-api-v1-projects-segments-create",
    description: ``,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await mcpApiV1ProjectsSegmentsCreate(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
