/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1ProjectsFeaturesList } from "../../funcs/mcpApiV1ProjectsFeaturesList.js";
import { ApiV1ProjectsFeaturesListRequest$zodSchema } from "../../models/apiv1projectsfeatureslistop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1ProjectsFeaturesListRequest$zodSchema,
};

export const tool$mcpApiV1ProjectsFeaturesList: ToolDefinition<typeof args> = {
  name: "mcp-api-v1-projects-features-list",
  description: ``,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await mcpApiV1ProjectsFeaturesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
