/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1ProjectsFeaturesCodeReferencesRetrieve } from "../../funcs/mcpApiV1ProjectsFeaturesCodeReferencesRetrieve.js";
import { ApiV1ProjectsFeaturesCodeReferencesRetrieveRequest$zodSchema } from "../../models/apiv1projectsfeaturescodereferencesretrieveop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1ProjectsFeaturesCodeReferencesRetrieveRequest$zodSchema,
};

export const tool$mcpApiV1ProjectsFeaturesCodeReferencesRetrieve:
  ToolDefinition<typeof args> = {
    name: "mcp-api-v1-projects-features-code-references-f2e",
    description:
      `API view to retrieve code references for a specific feature in a project`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await mcpApiV1ProjectsFeaturesCodeReferencesRetrieve(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
