/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpApiV1OrganisationsList } from "../../funcs/mcpApiV1OrganisationsList.js";
import { ApiV1OrganisationsListRequest$zodSchema } from "../../models/apiv1organisationslistop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ApiV1OrganisationsListRequest$zodSchema.optional(),
};

export const tool$mcpApiV1OrganisationsList: ToolDefinition<typeof args> = {
  name: "mcp-api-v1-organisations-list",
  description: ``,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await mcpApiV1OrganisationsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
