/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { FlagsmithCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool, registerDynamicTools } from "./tools.js";
import { tool$mcpApiV1EnvironmentsCreateChangeRequestCreate } from "./tools/mcpApiV1EnvironmentsCreateChangeRequestCreate.js";
import { tool$mcpApiV1EnvironmentsFeaturesVersionsCreate } from "./tools/mcpApiV1EnvironmentsFeaturesVersionsCreate.js";
import { tool$mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesCreate } from "./tools/mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesCreate.js";
import { tool$mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesList } from "./tools/mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesList.js";
import { tool$mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesUpdate } from "./tools/mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesUpdate.js";
import { tool$mcpApiV1EnvironmentsFeaturesVersionsList } from "./tools/mcpApiV1EnvironmentsFeaturesVersionsList.js";
import { tool$mcpApiV1EnvironmentsList } from "./tools/mcpApiV1EnvironmentsList.js";
import { tool$mcpApiV1EnvironmentsListChangeRequestsRetrieve } from "./tools/mcpApiV1EnvironmentsListChangeRequestsRetrieve.js";
import { tool$mcpApiV1OrganisationsGroupsList } from "./tools/mcpApiV1OrganisationsGroupsList.js";
import { tool$mcpApiV1OrganisationsInvitesCreate } from "./tools/mcpApiV1OrganisationsInvitesCreate.js";
import { tool$mcpApiV1OrganisationsInvitesList } from "./tools/mcpApiV1OrganisationsInvitesList.js";
import { tool$mcpApiV1OrganisationsList } from "./tools/mcpApiV1OrganisationsList.js";
import { tool$mcpApiV1OrganisationsProjectsRetrieve } from "./tools/mcpApiV1OrganisationsProjectsRetrieve.js";
import { tool$mcpApiV1OrganisationsRolesList } from "./tools/mcpApiV1OrganisationsRolesList.js";
import { tool$mcpApiV1ProjectsChangeRequestsList } from "./tools/mcpApiV1ProjectsChangeRequestsList.js";
import { tool$mcpApiV1ProjectsEnvironmentsRetrieve } from "./tools/mcpApiV1ProjectsEnvironmentsRetrieve.js";
import { tool$mcpApiV1ProjectsFeatureHealthEventsList } from "./tools/mcpApiV1ProjectsFeatureHealthEventsList.js";
import { tool$mcpApiV1ProjectsFeaturesCodeReferencesRetrieve } from "./tools/mcpApiV1ProjectsFeaturesCodeReferencesRetrieve.js";
import { tool$mcpApiV1ProjectsFeaturesCreate } from "./tools/mcpApiV1ProjectsFeaturesCreate.js";
import { tool$mcpApiV1ProjectsFeaturesEvaluationDataRetrieve } from "./tools/mcpApiV1ProjectsFeaturesEvaluationDataRetrieve.js";
import { tool$mcpApiV1ProjectsFeaturesFeatureExternalResourcesList } from "./tools/mcpApiV1ProjectsFeaturesFeatureExternalResourcesList.js";
import { tool$mcpApiV1ProjectsFeaturesList } from "./tools/mcpApiV1ProjectsFeaturesList.js";
import { tool$mcpApiV1ProjectsFeaturesMvOptionsCreate } from "./tools/mcpApiV1ProjectsFeaturesMvOptionsCreate.js";
import { tool$mcpApiV1ProjectsFeaturesMvOptionsDestroy } from "./tools/mcpApiV1ProjectsFeaturesMvOptionsDestroy.js";
import { tool$mcpApiV1ProjectsFeaturesMvOptionsList } from "./tools/mcpApiV1ProjectsFeaturesMvOptionsList.js";
import { tool$mcpApiV1ProjectsFeaturesMvOptionsUpdate } from "./tools/mcpApiV1ProjectsFeaturesMvOptionsUpdate.js";
import { tool$mcpApiV1ProjectsFeaturesRetrieve } from "./tools/mcpApiV1ProjectsFeaturesRetrieve.js";
import { tool$mcpApiV1ProjectsFeaturesUpdate } from "./tools/mcpApiV1ProjectsFeaturesUpdate.js";
import { tool$mcpApiV1ProjectsReleasePipelinesAddFeatureCreate } from "./tools/mcpApiV1ProjectsReleasePipelinesAddFeatureCreate.js";
import { tool$mcpApiV1ProjectsReleasePipelinesList } from "./tools/mcpApiV1ProjectsReleasePipelinesList.js";
import { tool$mcpApiV1ProjectsReleasePipelinesRetrieve } from "./tools/mcpApiV1ProjectsReleasePipelinesRetrieve.js";
import { tool$mcpApiV1ProjectsRetrieve } from "./tools/mcpApiV1ProjectsRetrieve.js";
import { tool$mcpApiV1ProjectsSegmentsCreate } from "./tools/mcpApiV1ProjectsSegmentsCreate.js";
import { tool$mcpApiV1ProjectsSegmentsList } from "./tools/mcpApiV1ProjectsSegmentsList.js";
import { tool$mcpApiV1ProjectsSegmentsRetrieve } from "./tools/mcpApiV1ProjectsSegmentsRetrieve.js";
import { tool$mcpApiV1ProjectsSegmentsUpdate } from "./tools/mcpApiV1ProjectsSegmentsUpdate.js";
import { tool$mcpApiV1ProjectsUpdate } from "./tools/mcpApiV1ProjectsUpdate.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => FlagsmithCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Flagsmith",
    version: "0.0.1",
  });

  const getClient = deps.getSDK || (() =>
    new FlagsmithCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$mcpApiV1EnvironmentsList);
  tool(tool$mcpApiV1EnvironmentsCreateChangeRequestCreate);
  tool(tool$mcpApiV1EnvironmentsListChangeRequestsRetrieve);
  tool(tool$mcpApiV1EnvironmentsFeaturesVersionsList);
  tool(tool$mcpApiV1EnvironmentsFeaturesVersionsCreate);
  tool(tool$mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesList);
  tool(tool$mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesCreate);
  tool(tool$mcpApiV1EnvironmentsFeaturesVersionsFeaturestatesUpdate);
  tool(tool$mcpApiV1OrganisationsList);
  tool(tool$mcpApiV1OrganisationsGroupsList);
  tool(tool$mcpApiV1OrganisationsInvitesList);
  tool(tool$mcpApiV1OrganisationsInvitesCreate);
  tool(tool$mcpApiV1OrganisationsRolesList);
  tool(tool$mcpApiV1OrganisationsProjectsRetrieve);
  tool(tool$mcpApiV1ProjectsRetrieve);
  tool(tool$mcpApiV1ProjectsUpdate);
  tool(tool$mcpApiV1ProjectsEnvironmentsRetrieve);
  tool(tool$mcpApiV1ProjectsChangeRequestsList);
  tool(tool$mcpApiV1ProjectsFeatureHealthEventsList);
  tool(tool$mcpApiV1ProjectsFeaturesList);
  tool(tool$mcpApiV1ProjectsFeaturesCreate);
  tool(tool$mcpApiV1ProjectsFeaturesCodeReferencesRetrieve);
  tool(tool$mcpApiV1ProjectsFeaturesFeatureExternalResourcesList);
  tool(tool$mcpApiV1ProjectsFeaturesMvOptionsList);
  tool(tool$mcpApiV1ProjectsFeaturesMvOptionsCreate);
  tool(tool$mcpApiV1ProjectsFeaturesMvOptionsUpdate);
  tool(tool$mcpApiV1ProjectsFeaturesMvOptionsDestroy);
  tool(tool$mcpApiV1ProjectsFeaturesRetrieve);
  tool(tool$mcpApiV1ProjectsFeaturesUpdate);
  tool(tool$mcpApiV1ProjectsFeaturesEvaluationDataRetrieve);
  tool(tool$mcpApiV1ProjectsReleasePipelinesList);
  tool(tool$mcpApiV1ProjectsReleasePipelinesRetrieve);
  tool(tool$mcpApiV1ProjectsReleasePipelinesAddFeatureCreate);
  tool(tool$mcpApiV1ProjectsSegmentsList);
  tool(tool$mcpApiV1ProjectsSegmentsCreate);
  tool(tool$mcpApiV1ProjectsSegmentsRetrieve);
  tool(tool$mcpApiV1ProjectsSegmentsUpdate);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
