/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `TOGGLE_FEATURE` - Enable/Disable Feature for the environment
 *
 * @remarks
 * * `UPDATE_FEATURE_VALUE` - Update Feature Value for the environment
 * * `TOGGLE_FEATURE_FOR_SEGMENT` - Enable/Disable Feature for a specific segment
 * * `UPDATE_FEATURE_VALUE_FOR_SEGMENT` - Update Feature Value for a specific segment
 * * `PHASED_ROLLOUT` - Create Phased Rollout
 */
export const ActionTypeEnum = {
  ToggleFeature: "TOGGLE_FEATURE",
  UpdateFeatureValue: "UPDATE_FEATURE_VALUE",
  ToggleFeatureForSegment: "TOGGLE_FEATURE_FOR_SEGMENT",
  UpdateFeatureValueForSegment: "UPDATE_FEATURE_VALUE_FOR_SEGMENT",
  PhasedRollout: "PHASED_ROLLOUT",
} as const;
/**
 * * `TOGGLE_FEATURE` - Enable/Disable Feature for the environment
 *
 * @remarks
 * * `UPDATE_FEATURE_VALUE` - Update Feature Value for the environment
 * * `TOGGLE_FEATURE_FOR_SEGMENT` - Enable/Disable Feature for a specific segment
 * * `UPDATE_FEATURE_VALUE_FOR_SEGMENT` - Update Feature Value for a specific segment
 * * `PHASED_ROLLOUT` - Create Phased Rollout
 */
export type ActionTypeEnum = ClosedEnum<typeof ActionTypeEnum>;

export const ActionTypeEnum$zodSchema = z.enum([
  "TOGGLE_FEATURE",
  "UPDATE_FEATURE_VALUE",
  "TOGGLE_FEATURE_FOR_SEGMENT",
  "UPDATE_FEATURE_VALUE_FOR_SEGMENT",
  "PHASED_ROLLOUT",
]).describe(
  "* `TOGGLE_FEATURE` - Enable/Disable Feature for the environment\n* `UPDATE_FEATURE_VALUE` - Update Feature Value for the environment\n* `TOGGLE_FEATURE_FOR_SEGMENT` - Enable/Disable Feature for a specific segment\n* `UPDATE_FEATURE_VALUE_FOR_SEGMENT` - Update Feature Value for a specific segment\n* `PHASED_ROLLOUT` - Create Phased Rollout",
);
