/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomEnvironmentFeatureVersionFeatureStateInput,
  CustomEnvironmentFeatureVersionFeatureStateInput$zodSchema,
} from "./customenvironmentfeatureversionfeaturestateinput.js";

export type ApiV1EnvironmentsFeaturesVersionsFeaturestatesUpdateRequest = {
  environment_feature_version_pk: string | null;
  environment_pk: number;
  feature_pk: number;
  id: number;
  body: CustomEnvironmentFeatureVersionFeatureStateInput;
};

export const ApiV1EnvironmentsFeaturesVersionsFeaturestatesUpdateRequest$zodSchema:
  z.ZodType<ApiV1EnvironmentsFeaturesVersionsFeaturestatesUpdateRequest> = z
    .object({
      body: CustomEnvironmentFeatureVersionFeatureStateInput$zodSchema,
      environment_feature_version_pk: z.string().nullable(),
      environment_pk: z.int(),
      feature_pk: z.int(),
      id: z.int().describe(
        "A unique integer value identifying this feature state.",
      ),
    });
