/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `ASC` - ASC
 *
 * @remarks
 * * `DESC` - DESC
 */
export const SortDirection = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
/**
 * * `ASC` - ASC
 *
 * @remarks
 * * `DESC` - DESC
 */
export type SortDirection = ClosedEnum<typeof SortDirection>;

export const SortDirection$zodSchema = z.enum([
  "ASC",
  "DESC",
]).describe("* `ASC` - ASC\n* `DESC` - DESC");

/**
 * * `created_date` - created_date
 *
 * @remarks
 * * `name` - name
 */
export const SortField = {
  CreatedDate: "created_date",
  Name: "name",
} as const;
/**
 * * `created_date` - created_date
 *
 * @remarks
 * * `name` - name
 */
export type SortField = ClosedEnum<typeof SortField>;

export const SortField$zodSchema = z.enum([
  "created_date",
  "name",
]).describe("* `created_date` - created_date\n* `name` - name");

/**
 * * `UNION` - UNION
 *
 * @remarks
 * * `INTERSECTION` - INTERSECTION
 */
export const TagStrategy = {
  Union: "UNION",
  Intersection: "INTERSECTION",
} as const;
/**
 * * `UNION` - UNION
 *
 * @remarks
 * * `INTERSECTION` - INTERSECTION
 */
export type TagStrategy = ClosedEnum<typeof TagStrategy>;

export const TagStrategy$zodSchema = z.enum([
  "UNION",
  "INTERSECTION",
]).describe("* `UNION` - UNION\n* `INTERSECTION` - INTERSECTION");

export type ApiV1ProjectsFeaturesListRequest = {
  environment?: number | undefined;
  group_owners?: string | undefined;
  identity?: string | undefined;
  is_archived?: boolean | undefined;
  is_enabled?: boolean | null | undefined;
  owners?: string | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  project_pk: number;
  search?: string | undefined;
  segment?: number | undefined;
  sort_direction?: SortDirection | undefined;
  sort_field?: SortField | undefined;
  tag_strategy?: TagStrategy | undefined;
  tags?: string | undefined;
  value_search?: string | undefined;
};

export const ApiV1ProjectsFeaturesListRequest$zodSchema: z.ZodType<
  ApiV1ProjectsFeaturesListRequest
> = z.object({
  environment: z.int().describe(
    "Integer ID of the environment to view features in the context of.",
  ).optional(),
  group_owners: z.string().describe(
    "Comma separated list of group owner ids to filter on",
  ).optional(),
  identity: z.string().describe(
    "ID of the identity to sort features with identity overrides first.",
  ).optional(),
  is_archived: z.boolean().optional(),
  is_enabled: z.boolean().describe(
    "Boolean value to filter features as enabled or disabled.",
  ).nullable().optional(),
  owners: z.string().describe("Comma separated list of owner ids to filter on")
    .optional(),
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
  page_size: z.int().describe("Number of results to return per page.")
    .optional(),
  project_pk: z.int(),
  search: z.string().optional(),
  segment: z.int().describe(
    "Integer ID of the segment to retrieve segment overrides for.",
  ).optional(),
  sort_direction: SortDirection$zodSchema.default("ASC"),
  sort_field: SortField$zodSchema.default("created_date"),
  tag_strategy: TagStrategy$zodSchema.default("INTERSECTION"),
  tags: z.string().describe(
    "Comma separated list of tag ids to filter on (AND with INTERSECTION, and OR with UNION via tag_strategy)",
  ).optional(),
  value_search: z.string().describe(
    "Value of type int, string, or boolean to filter features based on their values",
  ).optional(),
});
