/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MultivariateFeatureOptionInput,
  MultivariateFeatureOptionInput$zodSchema,
} from "./multivariatefeatureoption.js";

export type ApiV1ProjectsFeaturesMvOptionsUpdateRequest = {
  feature_pk: number;
  id: number;
  project_pk: string;
  body: MultivariateFeatureOptionInput;
};

export const ApiV1ProjectsFeaturesMvOptionsUpdateRequest$zodSchema: z.ZodType<
  ApiV1ProjectsFeaturesMvOptionsUpdateRequest
> = z.object({
  body: MultivariateFeatureOptionInput$zodSchema,
  feature_pk: z.int(),
  id: z.int().describe(
    "A unique integer value identifying this multivariate feature option.",
  ),
  project_pk: z.string(),
});
