/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsFeaturesCodeReferencesRetrieveRequest = {
  feature_pk: number;
  project_pk: number;
};

export const ApiV1ProjectsFeaturesCodeReferencesRetrieveRequest$zodSchema:
  z.ZodType<ApiV1ProjectsFeaturesCodeReferencesRetrieveRequest> = z.object({
    feature_pk: z.int(),
    project_pk: z.int(),
  });
