/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomEnvironmentFeatureVersionFeatureStateInput,
  CustomEnvironmentFeatureVersionFeatureStateInput$zodSchema,
} from "./customenvironmentfeatureversionfeaturestateinput.js";

export type ApiV1EnvironmentsFeaturesVersionsFeaturestatesCreateRequest = {
  environment_feature_version_pk: string | null;
  environment_pk: number;
  feature_pk: number;
  body: CustomEnvironmentFeatureVersionFeatureStateInput;
};

export const ApiV1EnvironmentsFeaturesVersionsFeaturestatesCreateRequest$zodSchema:
  z.ZodType<ApiV1EnvironmentsFeaturesVersionsFeaturestatesCreateRequest> = z
    .object({
      body: CustomEnvironmentFeatureVersionFeatureStateInput$zodSchema,
      environment_feature_version_pk: z.string().nullable(),
      environment_pk: z.int(),
      feature_pk: z.int(),
    });
