/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsFeaturesEvaluationDataRetrieveRequest = {
  client_application_name?: string | null | undefined;
  client_application_version?: string | null | undefined;
  environment_id: number;
  id: number;
  period?: number | undefined;
  project_pk: number;
  user_agent?: string | null | undefined;
};

export const ApiV1ProjectsFeaturesEvaluationDataRetrieveRequest$zodSchema:
  z.ZodType<ApiV1ProjectsFeaturesEvaluationDataRetrieveRequest> = z.object({
    client_application_name: z.string().nullable().optional(),
    client_application_version: z.string().nullable().optional(),
    environment_id: z.int(),
    id: z.int().describe("A unique integer value identifying this feature."),
    period: z.int().default(30).describe("number of days"),
    project_pk: z.int(),
    user_agent: z.string().nullable().optional(),
  });
