/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1EnvironmentsFeaturesVersionsFeaturestatesListRequest = {
  environment_feature_version_pk: string | null;
  environment_pk: number;
  feature_pk: number;
};

export const ApiV1EnvironmentsFeaturesVersionsFeaturestatesListRequest$zodSchema:
  z.ZodType<ApiV1EnvironmentsFeaturesVersionsFeaturestatesListRequest> = z
    .object({
      environment_feature_version_pk: z.string().nullable(),
      environment_pk: z.int(),
      feature_pk: z.int(),
    });
