/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChangeRequestList,
  ChangeRequestList$zodSchema,
} from "./changerequestlist.js";
import { WorkflowsError, WorkflowsError$zodSchema } from "./workflowserror.js";

export type ApiV1EnvironmentsListChangeRequestsRetrieveRequest = {
  committed?: boolean | null | undefined;
  environment_api_key: string;
  feature_id?: number | undefined;
  live_from_after?: string | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  search?: string | undefined;
  segment_id?: number | undefined;
};

export const ApiV1EnvironmentsListChangeRequestsRetrieveRequest$zodSchema:
  z.ZodType<ApiV1EnvironmentsListChangeRequestsRetrieveRequest> = z.object({
    committed: z.boolean().describe(
      "Filter on the committed status of a change request.",
    ).nullable().optional(),
    environment_api_key: z.string(),
    feature_id: z.int().describe("Filter for a particular feature.").optional(),
    live_from_after: z.iso.datetime({ offset: true }).describe(
      "Filter change requests due to go live after this datetime.",
    ).optional(),
    page: z.int().describe("A page number within the paginated result set.")
      .optional(),
    page_size: z.int().describe("Number of results to return per page.")
      .optional(),
    search: z.string().describe("Fuzzy search across Change Request titles.")
      .optional(),
    segment_id: z.int().describe(
      "Filter change requests which match a specific segment id.",
    ).optional(),
  });

export type ApiV1EnvironmentsListChangeRequestsRetrieveResponse =
  | WorkflowsError
  | ChangeRequestList;

export const ApiV1EnvironmentsListChangeRequestsRetrieveResponse$zodSchema:
  z.ZodType<ApiV1EnvironmentsListChangeRequestsRetrieveResponse> = z.union([
    WorkflowsError$zodSchema,
    ChangeRequestList$zodSchema,
  ]);
