/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1OrganisationsInvitesListRequest = {
  organisation_pk: number;
  page?: number | undefined;
};

export const ApiV1OrganisationsInvitesListRequest$zodSchema: z.ZodType<
  ApiV1OrganisationsInvitesListRequest
> = z.object({
  organisation_pk: z.int(),
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
});
