/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1OrganisationsRolesListRequest = {
  organisation_pk: string;
  page?: number | undefined;
};

export const ApiV1OrganisationsRolesListRequest$zodSchema: z.ZodType<
  ApiV1OrganisationsRolesListRequest
> = z.object({
  organisation_pk: z.string(),
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
});
