/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { InviteInput, InviteInput$zodSchema } from "./inviteinput.js";

export type ApiV1OrganisationsInvitesCreateRequest = {
  organisation_pk: number;
  body: InviteInput;
};

export const ApiV1OrganisationsInvitesCreateRequest$zodSchema: z.ZodType<
  ApiV1OrganisationsInvitesCreateRequest
> = z.object({
  body: InviteInput$zodSchema,
  organisation_pk: z.int(),
});
