/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MultivariateFeatureOptionInput,
  MultivariateFeatureOptionInput$zodSchema,
} from "./multivariatefeatureoption.js";

export type ApiV1ProjectsFeaturesMvOptionsCreateRequest = {
  feature_pk: number;
  project_pk: string;
  body: MultivariateFeatureOptionInput;
};

export const ApiV1ProjectsFeaturesMvOptionsCreateRequest$zodSchema: z.ZodType<
  ApiV1ProjectsFeaturesMvOptionsCreateRequest
> = z.object({
  body: MultivariateFeatureOptionInput$zodSchema,
  feature_pk: z.int(),
  project_pk: z.string(),
});
