/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PaginatedProjectChangeRequestListList,
  PaginatedProjectChangeRequestListList$zodSchema,
} from "./paginatedprojectchangerequestlistlist.js";
import { WorkflowsError, WorkflowsError$zodSchema } from "./workflowserror.js";

export type ApiV1ProjectsChangeRequestsListRequest = {
  committed?: boolean | null | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  project_pk: string;
  search?: string | undefined;
  segment_id?: number | undefined;
};

export const ApiV1ProjectsChangeRequestsListRequest$zodSchema: z.ZodType<
  ApiV1ProjectsChangeRequestsListRequest
> = z.object({
  committed: z.boolean().describe(
    "Filter on the committed status of a change request.",
  ).nullable().optional(),
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
  page_size: z.int().describe("Number of results to return per page.")
    .optional(),
  project_pk: z.string(),
  search: z.string().describe("Fuzzy search across Change Request titles.")
    .optional(),
  segment_id: z.int().describe(
    "Filter change requests which match a specific segment id.",
  ).optional(),
});

export type ApiV1ProjectsChangeRequestsListResponse =
  | PaginatedProjectChangeRequestListList
  | WorkflowsError;

export const ApiV1ProjectsChangeRequestsListResponse$zodSchema: z.ZodType<
  ApiV1ProjectsChangeRequestsListResponse
> = z.union([
  PaginatedProjectChangeRequestListList$zodSchema,
  WorkflowsError$zodSchema,
]);
