/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsFeaturesMvOptionsListRequest = {
  feature_pk: number;
  page?: number | undefined;
  project_pk: string;
};

export const ApiV1ProjectsFeaturesMvOptionsListRequest$zodSchema: z.ZodType<
  ApiV1ProjectsFeaturesMvOptionsListRequest
> = z.object({
  feature_pk: z.int(),
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
  project_pk: z.string(),
});
