/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsFeaturesRetrieveRequest = {
  id: number;
  project_pk: number;
};

export const ApiV1ProjectsFeaturesRetrieveRequest$zodSchema: z.ZodType<
  ApiV1ProjectsFeaturesRetrieveRequest
> = z.object({
  id: z.int().describe("A unique integer value identifying this feature."),
  project_pk: z.int(),
});
