/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsFeaturesMvOptionsDestroyRequest = {
  feature_pk: number;
  id: number;
  project_pk: string;
};

export const ApiV1ProjectsFeaturesMvOptionsDestroyRequest$zodSchema: z.ZodType<
  ApiV1ProjectsFeaturesMvOptionsDestroyRequest
> = z.object({
  feature_pk: z.int(),
  id: z.int().describe(
    "A unique integer value identifying this multivariate feature option.",
  ),
  project_pk: z.string(),
});
