/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsReleasePipelinesListRequest = {
  ordering?: string | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  project_pk: string;
};

export const ApiV1ProjectsReleasePipelinesListRequest$zodSchema: z.ZodType<
  ApiV1ProjectsReleasePipelinesListRequest
> = z.object({
  ordering: z.string().describe("Which field to use when ordering the results.")
    .optional(),
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
  page_size: z.int().describe("Number of results to return per page.")
    .optional(),
  project_pk: z.string(),
});
