/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsSegmentsListRequest = {
  identity?: string | undefined;
  include_feature_specific?: boolean | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  project_pk: number;
  q?: string | undefined;
};

export const ApiV1ProjectsSegmentsListRequest$zodSchema: z.ZodType<
  ApiV1ProjectsSegmentsListRequest
> = z.object({
  identity: z.string().describe(
    "Optionally provide the id of an identity to get only the segments they match",
  ).optional(),
  include_feature_specific: z.boolean().default(true),
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
  page_size: z.int().describe("Number of results to return per page.")
    .optional(),
  project_pk: z.int(),
  q: z.string().describe(
    "Search term to find segment with given term in their name",
  ).optional(),
});
