/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1EnvironmentsListRequest = {
  page?: number | undefined;
  project?: number | undefined;
};

export const ApiV1EnvironmentsListRequest$zodSchema: z.ZodType<
  ApiV1EnvironmentsListRequest
> = z.object({
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
  project: z.int().describe("ID of the project to filter by.").optional(),
});
