/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SegmentInput, SegmentInput$zodSchema } from "./segmentinput.js";

export type ApiV1ProjectsSegmentsUpdateRequest = {
  id: number;
  project_pk: number;
  body: SegmentInput;
};

export const ApiV1ProjectsSegmentsUpdateRequest$zodSchema: z.ZodType<
  ApiV1ProjectsSegmentsUpdateRequest
> = z.object({
  body: SegmentInput$zodSchema,
  id: z.int().describe("A unique integer value identifying this segment."),
  project_pk: z.int(),
});
