/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateFeatureInput,
  UpdateFeatureInput$zodSchema,
} from "./updatefeatureinput.js";

export type ApiV1ProjectsFeaturesUpdateRequest = {
  id: number;
  project_pk: number;
  body?: UpdateFeatureInput | undefined;
};

export const ApiV1ProjectsFeaturesUpdateRequest$zodSchema: z.ZodType<
  ApiV1ProjectsFeaturesUpdateRequest
> = z.object({
  body: UpdateFeatureInput$zodSchema.optional(),
  id: z.int().describe("A unique integer value identifying this feature."),
  project_pk: z.int(),
});
