/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsSegmentsRetrieveRequest = {
  id: number;
  project_pk: number;
};

export const ApiV1ProjectsSegmentsRetrieveRequest$zodSchema: z.ZodType<
  ApiV1ProjectsSegmentsRetrieveRequest
> = z.object({
  id: z.int().describe("A unique integer value identifying this segment."),
  project_pk: z.int(),
});
