/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChangeRequestCreate,
  ChangeRequestCreate$zodSchema,
} from "./changerequestcreate.js";
import {
  ChangeRequestCreateInput,
  ChangeRequestCreateInput$zodSchema,
} from "./changerequestcreateinput.js";
import { WorkflowsError, WorkflowsError$zodSchema } from "./workflowserror.js";

export type ApiV1EnvironmentsCreateChangeRequestCreateRequest = {
  environment_api_key: string;
  body: ChangeRequestCreateInput;
};

export const ApiV1EnvironmentsCreateChangeRequestCreateRequest$zodSchema:
  z.ZodType<ApiV1EnvironmentsCreateChangeRequestCreateRequest> = z.object({
    body: ChangeRequestCreateInput$zodSchema,
    environment_api_key: z.string(),
  });

export type ApiV1EnvironmentsCreateChangeRequestCreateResponse =
  | ChangeRequestCreate
  | WorkflowsError;

export const ApiV1EnvironmentsCreateChangeRequestCreateResponse$zodSchema:
  z.ZodType<ApiV1EnvironmentsCreateChangeRequestCreateResponse> = z.union([
    ChangeRequestCreate$zodSchema,
    WorkflowsError$zodSchema,
  ]);
