/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1EnvironmentsFeaturesVersionsListRequest = {
  environment_pk: number;
  feature_pk: number;
  page?: number | undefined;
  page_size?: number | undefined;
};

export const ApiV1EnvironmentsFeaturesVersionsListRequest$zodSchema: z.ZodType<
  ApiV1EnvironmentsFeaturesVersionsListRequest
> = z.object({
  environment_pk: z.int(),
  feature_pk: z.int(),
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
  page_size: z.int().describe("Number of results to return per page.")
    .optional(),
});
