/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsReleasePipelinesRetrieveRequest = {
  id: string;
  project_pk: string;
};

export const ApiV1ProjectsReleasePipelinesRetrieveRequest$zodSchema: z.ZodType<
  ApiV1ProjectsReleasePipelinesRetrieveRequest
> = z.object({
  id: z.string(),
  project_pk: z.string(),
});
