/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EnvironmentFeatureVersionCreateInput,
  EnvironmentFeatureVersionCreateInput$zodSchema,
} from "./environmentfeatureversioncreateinput.js";

export type ApiV1EnvironmentsFeaturesVersionsCreateRequest = {
  environment_pk: number;
  feature_pk: number;
  body?: EnvironmentFeatureVersionCreateInput | undefined;
};

export const ApiV1EnvironmentsFeaturesVersionsCreateRequest$zodSchema:
  z.ZodType<ApiV1EnvironmentsFeaturesVersionsCreateRequest> = z.object({
    body: EnvironmentFeatureVersionCreateInput$zodSchema.optional(),
    environment_pk: z.int(),
    feature_pk: z.int(),
  });
