/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsRetrieveRequest = { id: number };

export const ApiV1ProjectsRetrieveRequest$zodSchema: z.ZodType<
  ApiV1ProjectsRetrieveRequest
> = z.object({
  id: z.int().describe("A unique integer value identifying this project."),
});
