/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ListFeatureInput,
  ListFeatureInput$zodSchema,
} from "./listfeatureinput.js";

export type ApiV1ProjectsFeaturesCreateRequest = {
  project_pk: number;
  body: ListFeatureInput;
};

export const ApiV1ProjectsFeaturesCreateRequest$zodSchema: z.ZodType<
  ApiV1ProjectsFeaturesCreateRequest
> = z.object({
  body: ListFeatureInput$zodSchema,
  project_pk: z.int(),
});
