/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1ProjectsFeatureHealthEventsListRequest = {
  project_pk: string;
};

export const ApiV1ProjectsFeatureHealthEventsListRequest$zodSchema: z.ZodType<
  ApiV1ProjectsFeatureHealthEventsListRequest
> = z.object({
  project_pk: z.string(),
});
