/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SegmentInput, SegmentInput$zodSchema } from "./segmentinput.js";

export type ApiV1ProjectsSegmentsCreateRequest = {
  project_pk: number;
  body: SegmentInput;
};

export const ApiV1ProjectsSegmentsCreateRequest$zodSchema: z.ZodType<
  ApiV1ProjectsSegmentsCreateRequest
> = z.object({
  body: SegmentInput$zodSchema,
  project_pk: z.int(),
});
