/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ReleasePipelineInput,
  ReleasePipelineInput$zodSchema,
} from "./releasepipelineinput.js";

export type ApiV1ProjectsReleasePipelinesAddFeatureCreateRequest = {
  id: string;
  project_pk: string;
  body: ReleasePipelineInput;
};

export const ApiV1ProjectsReleasePipelinesAddFeatureCreateRequest$zodSchema:
  z.ZodType<ApiV1ProjectsReleasePipelinesAddFeatureCreateRequest> = z.object({
    body: ReleasePipelineInput$zodSchema,
    id: z.string(),
    project_pk: z.string(),
  });
