/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1OrganisationsProjectsRetrieveRequest = { id: number };

export const ApiV1OrganisationsProjectsRetrieveRequest$zodSchema: z.ZodType<
  ApiV1OrganisationsProjectsRetrieveRequest
> = z.object({
  id: z.int().describe("A unique integer value identifying this organisation."),
});
