/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ProjectUpdateInput,
  ProjectUpdateInput$zodSchema,
} from "./projectupdateinput.js";

export type ApiV1ProjectsUpdateRequest = {
  id: number;
  body: ProjectUpdateInput;
};

export const ApiV1ProjectsUpdateRequest$zodSchema: z.ZodType<
  ApiV1ProjectsUpdateRequest
> = z.object({
  body: ProjectUpdateInput$zodSchema,
  id: z.int().describe("A unique integer value identifying this project."),
});
