/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiV1OrganisationsListRequest = { page?: number | undefined };

export const ApiV1OrganisationsListRequest$zodSchema: z.ZodType<
  ApiV1OrganisationsListRequest
> = z.object({
  page: z.int().describe("A page number within the paginated result set.")
    .optional(),
});
