/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `ACTIVE` - Active
 *
 * @remarks
 * * `DUNNING` - Dunning
 */
export const BillingStatusEnum = {
  Active: "ACTIVE",
  Dunning: "DUNNING",
} as const;
/**
 * * `ACTIVE` - Active
 *
 * @remarks
 * * `DUNNING` - Dunning
 */
export type BillingStatusEnum = ClosedEnum<typeof BillingStatusEnum>;

export const BillingStatusEnum$zodSchema = z.enum([
  "ACTIVE",
  "DUNNING",
]).describe("* `ACTIVE` - Active\n* `DUNNING` - Dunning");
