/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Adds nested create feature
 */
export type ChangeRequestGroupAssignment = { group: number };

export const ChangeRequestGroupAssignment$zodSchema: z.ZodType<
  ChangeRequestGroupAssignment
> = z.object({
  group: z.int(),
}).describe("Adds nested create feature");
