/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChangeRequestApproval,
  ChangeRequestApproval$zodSchema,
} from "./changerequestapproval.js";
import {
  ChangeRequestGroupAssignment,
  ChangeRequestGroupAssignment$zodSchema,
} from "./changerequestgroupassignment.js";
import {
  CreateChangeRequestFeatureState,
  CreateChangeRequestFeatureState$zodSchema,
} from "./createchangerequestfeaturestate.js";
import {
  VersionChangeSet,
  VersionChangeSet$zodSchema,
} from "./versionchangeset.js";

/**
 * Adds nested create feature
 */
export type ChangeRequestCreate = {
  id?: number | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  title: string;
  description?: string | null | undefined;
  feature_states: Array<CreateChangeRequestFeatureState>;
  deleted_at?: string | null | undefined;
  environment?: number | null | undefined;
  committed_at?: string | null | undefined;
  approvals?: Array<ChangeRequestApproval> | undefined;
  user?: number | null | undefined;
  committed_by?: number | null | undefined;
  group_assignments?: Array<ChangeRequestGroupAssignment> | undefined;
  environment_feature_versions?: Array<string> | undefined;
  change_sets?: Array<VersionChangeSet> | null | undefined;
  ignore_conflicts?: boolean | undefined;
};

export const ChangeRequestCreate$zodSchema: z.ZodType<ChangeRequestCreate> = z
  .object({
    approvals: z.array(ChangeRequestApproval$zodSchema).optional(),
    change_sets: z.array(VersionChangeSet$zodSchema).nullable().optional(),
    committed_at: z.iso.datetime({ offset: true }).nullable().optional(),
    committed_by: z.int().nullable().optional(),
    created_at: z.iso.datetime({ offset: true }).optional(),
    deleted_at: z.iso.datetime({ offset: true }).nullable().optional(),
    description: z.string().nullable().optional(),
    environment: z.int().nullable().optional(),
    environment_feature_versions: z.array(z.string()).optional(),
    feature_states: z.array(CreateChangeRequestFeatureState$zodSchema),
    group_assignments: z.array(ChangeRequestGroupAssignment$zodSchema)
      .optional(),
    id: z.int().optional(),
    ignore_conflicts: z.boolean().optional(),
    title: z.string(),
    updated_at: z.iso.datetime({ offset: true }).optional(),
    user: z.int().nullable().optional(),
  }).describe("Adds nested create feature");
