/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Adds nested create feature
 */
export type ChangeRequestApprovalInput = { user: number };

export const ChangeRequestApprovalInput$zodSchema: z.ZodType<
  ChangeRequestApprovalInput
> = z.object({
  user: z.int(),
}).describe("Adds nested create feature");
