/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChangeRequestApprovalInput,
  ChangeRequestApprovalInput$zodSchema,
} from "./changerequestapprovalinput.js";
import {
  ChangeRequestGroupAssignment,
  ChangeRequestGroupAssignment$zodSchema,
} from "./changerequestgroupassignment.js";
import {
  CreateChangeRequestFeatureStateInput,
  CreateChangeRequestFeatureStateInput$zodSchema,
} from "./createchangerequestfeaturestateinput.js";
import {
  VersionChangeSetInput,
  VersionChangeSetInput$zodSchema,
} from "./versionchangesetinput.js";

/**
 * Adds nested create feature
 */
export type ChangeRequestCreateInput = {
  title: string;
  description?: string | null | undefined;
  feature_states: Array<CreateChangeRequestFeatureStateInput>;
  approvals?: Array<ChangeRequestApprovalInput> | undefined;
  group_assignments?: Array<ChangeRequestGroupAssignment> | undefined;
  environment_feature_versions?: Array<string> | undefined;
  change_sets?: Array<VersionChangeSetInput> | null | undefined;
  ignore_conflicts?: boolean | undefined;
};

export const ChangeRequestCreateInput$zodSchema: z.ZodType<
  ChangeRequestCreateInput
> = z.object({
  approvals: z.array(ChangeRequestApprovalInput$zodSchema).optional(),
  change_sets: z.array(VersionChangeSetInput$zodSchema).nullable().optional(),
  description: z.string().nullable().optional(),
  environment_feature_versions: z.array(z.string()).optional(),
  feature_states: z.array(CreateChangeRequestFeatureStateInput$zodSchema),
  group_assignments: z.array(ChangeRequestGroupAssignment$zodSchema).optional(),
  ignore_conflicts: z.boolean().optional(),
  title: z.string(),
}).describe("Adds nested create feature");
