/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Adds nested create feature
 */
export type ChangeRequestApproval = {
  id?: number | undefined;
  user: number;
  approved_at?: string | null | undefined;
};

export const ChangeRequestApproval$zodSchema: z.ZodType<ChangeRequestApproval> =
  z.object({
    approved_at: z.iso.datetime({ offset: true }).nullable().optional(),
    id: z.int().optional(),
    user: z.int(),
  }).describe("Adds nested create feature");
