/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ChangeRequestList = {
  id?: number | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  title?: string | undefined;
  description?: string | null | undefined;
  user?: number | null | undefined;
  committed_at?: string | null | undefined;
  committed_by?: number | null | undefined;
  deleted_at?: string | null | undefined;
  live_from?: string | null | undefined;
  environment_feature_versions?: Array<string> | undefined;
  ignore_conflicts?: boolean | undefined;
};

export const ChangeRequestList$zodSchema: z.ZodType<ChangeRequestList> = z
  .object({
    committed_at: z.iso.datetime({ offset: true }).nullable().optional(),
    committed_by: z.int().nullable().optional(),
    created_at: z.iso.datetime({ offset: true }).optional(),
    deleted_at: z.iso.datetime({ offset: true }).nullable().optional(),
    description: z.string().nullable().optional(),
    environment_feature_versions: z.array(z.string()).optional(),
    id: z.int().optional(),
    ignore_conflicts: z.boolean().optional(),
    live_from: z.iso.datetime({ offset: true }).nullable().optional(),
    title: z.string().optional(),
    updated_at: z.iso.datetime({ offset: true }).optional(),
    user: z.int().nullable().optional(),
  });
