/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  VcsProviderEnum,
  VcsProviderEnum$zodSchema,
} from "./vcsproviderenum.js";

export type CodeReferenceDetail = {
  file_path: string;
  line_number: number;
  scanned_at: string;
  vcs_provider: VcsProviderEnum;
  repository_url: string;
  revision: string;
  permalink: string;
};

export const CodeReferenceDetail$zodSchema: z.ZodType<CodeReferenceDetail> = z
  .object({
    file_path: z.string(),
    line_number: z.int(),
    permalink: z.string(),
    repository_url: z.string(),
    revision: z.string(),
    scanned_at: z.iso.datetime({ offset: true }),
    vcs_provider: VcsProviderEnum$zodSchema,
  });
