/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConditionOperatorEnum,
  ConditionOperatorEnum$zodSchema,
} from "./conditionoperatorenum.js";

export type ConditionOutput = {
  id?: number | undefined;
  operator: ConditionOperatorEnum;
  property?: string | null | undefined;
  value?: string | null | undefined;
  description?: string | null | undefined;
};

export const ConditionOutput$zodSchema: z.ZodType<ConditionOutput> = z.object({
  description: z.string().nullable().optional(),
  id: z.int().optional(),
  operator: ConditionOperatorEnum$zodSchema,
  property: z.string().nullable().optional(),
  value: z.string().nullable().optional(),
});
