/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `EQUAL` - Exactly Matches
 *
 * @remarks
 * * `GREATER_THAN` - Greater than
 * * `LESS_THAN` - Less than
 * * `CONTAINS` - Contains
 * * `GREATER_THAN_INCLUSIVE` - Greater than or equal to
 * * `LESS_THAN_INCLUSIVE` - Less than or equal to
 * * `NOT_CONTAINS` - Does not contain
 * * `NOT_EQUAL` - Does not match
 * * `REGEX` - Matches regex
 * * `PERCENTAGE_SPLIT` - Percentage split
 * * `MODULO` - Modulo Operation
 * * `IS_SET` - Is set
 * * `IS_NOT_SET` - Is not set
 * * `IN` - In
 */
export const ConditionOperatorEnum = {
  Equal: "EQUAL",
  GreaterThan: "GREATER_THAN",
  LessThan: "LESS_THAN",
  Contains: "CONTAINS",
  GreaterThanInclusive: "GREATER_THAN_INCLUSIVE",
  LessThanInclusive: "LESS_THAN_INCLUSIVE",
  NotContains: "NOT_CONTAINS",
  NotEqual: "NOT_EQUAL",
  Regex: "REGEX",
  PercentageSplit: "PERCENTAGE_SPLIT",
  Modulo: "MODULO",
  IsSet: "IS_SET",
  IsNotSet: "IS_NOT_SET",
  In: "IN",
} as const;
/**
 * * `EQUAL` - Exactly Matches
 *
 * @remarks
 * * `GREATER_THAN` - Greater than
 * * `LESS_THAN` - Less than
 * * `CONTAINS` - Contains
 * * `GREATER_THAN_INCLUSIVE` - Greater than or equal to
 * * `LESS_THAN_INCLUSIVE` - Less than or equal to
 * * `NOT_CONTAINS` - Does not contain
 * * `NOT_EQUAL` - Does not match
 * * `REGEX` - Matches regex
 * * `PERCENTAGE_SPLIT` - Percentage split
 * * `MODULO` - Modulo Operation
 * * `IS_SET` - Is set
 * * `IS_NOT_SET` - Is not set
 * * `IN` - In
 */
export type ConditionOperatorEnum = ClosedEnum<typeof ConditionOperatorEnum>;

export const ConditionOperatorEnum$zodSchema = z.enum([
  "EQUAL",
  "GREATER_THAN",
  "LESS_THAN",
  "CONTAINS",
  "GREATER_THAN_INCLUSIVE",
  "LESS_THAN_INCLUSIVE",
  "NOT_CONTAINS",
  "NOT_EQUAL",
  "REGEX",
  "PERCENTAGE_SPLIT",
  "MODULO",
  "IS_SET",
  "IS_NOT_SET",
  "IN",
]).describe(
  "* `EQUAL` - Exactly Matches\n* `GREATER_THAN` - Greater than\n* `LESS_THAN` - Less than\n* `CONTAINS` - Contains\n* `GREATER_THAN_INCLUSIVE` - Greater than or equal to\n* `LESS_THAN_INCLUSIVE` - Less than or equal to\n* `NOT_CONTAINS` - Does not contain\n* `NOT_EQUAL` - Does not match\n* `REGEX` - Matches regex\n* `PERCENTAGE_SPLIT` - Percentage split\n* `MODULO` - Modulo Operation\n* `IS_SET` - Is set\n* `IS_NOT_SET` - Is not set\n* `IN` - In",
);
