/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConditionOperatorEnum,
  ConditionOperatorEnum$zodSchema,
} from "./conditionoperatorenum.js";

export type ConditionInput = {
  operator: ConditionOperatorEnum;
  property?: string | null | undefined;
  value?: string | null | undefined;
  description?: string | null | undefined;
  delete?: boolean | undefined;
};

export const ConditionInput$zodSchema: z.ZodType<ConditionInput> = z.object({
  delete: z.boolean().optional(),
  description: z.string().nullable().optional(),
  operator: ConditionOperatorEnum$zodSchema,
  property: z.string().nullable().optional(),
  value: z.string().nullable().optional(),
});
