/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FeatureStateValue1,
  FeatureStateValue1$zodSchema,
} from "./featurestatevalue1.js";
import {
  MultivariateFeatureStateValue1,
  MultivariateFeatureStateValue1$zodSchema,
} from "./multivariatefeaturestatevalue1.js";

/**
 * Adds nested create feature
 */
export type CreateChangeRequestFeatureState = {
  id?: number | undefined;
  feature: number;
  feature_segment?: number | null | undefined;
  enabled?: boolean | undefined;
  feature_state_value?: FeatureStateValue1 | undefined;
  multivariate_feature_state_values?:
    | Array<MultivariateFeatureStateValue1>
    | undefined;
  live_from?: string | null | undefined;
};

export const CreateChangeRequestFeatureState$zodSchema: z.ZodType<
  CreateChangeRequestFeatureState
> = z.object({
  enabled: z.boolean().optional(),
  feature: z.int(),
  feature_segment: z.int().nullable().optional(),
  feature_state_value: FeatureStateValue1$zodSchema.optional(),
  id: z.int().optional(),
  live_from: z.iso.datetime({ offset: true }).nullable().optional(),
  multivariate_feature_state_values: z.array(
    MultivariateFeatureStateValue1$zodSchema,
  ).optional(),
}).describe("Adds nested create feature");
