/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FeatureStateValue1,
  FeatureStateValue1$zodSchema,
} from "./featurestatevalue1.js";
import {
  MultivariateFeatureStateValueInput1,
  MultivariateFeatureStateValueInput1$zodSchema,
} from "./multivariatefeaturestatevalueinput1.js";

/**
 * Adds nested create feature
 */
export type CreateChangeRequestFeatureStateInput = {
  feature: number;
  feature_segment?: number | null | undefined;
  enabled?: boolean | undefined;
  feature_state_value?: FeatureStateValue1 | undefined;
  multivariate_feature_state_values?:
    | Array<MultivariateFeatureStateValueInput1>
    | undefined;
  live_from?: string | null | undefined;
};

export const CreateChangeRequestFeatureStateInput$zodSchema: z.ZodType<
  CreateChangeRequestFeatureStateInput
> = z.object({
  enabled: z.boolean().optional(),
  feature: z.int(),
  feature_segment: z.int().nullable().optional(),
  feature_state_value: FeatureStateValue1$zodSchema.optional(),
  live_from: z.iso.datetime({ offset: true }).nullable().optional(),
  multivariate_feature_state_values: z.array(
    MultivariateFeatureStateValueInput1$zodSchema,
  ).optional(),
}).describe("Adds nested create feature");
