/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CustomCreateSegmentOverrideFeatureSegment = {
  id?: number | undefined;
  segment: number;
  priority?: number | undefined;
  uuid?: string | undefined;
};

export const CustomCreateSegmentOverrideFeatureSegment$zodSchema: z.ZodType<
  CustomCreateSegmentOverrideFeatureSegment
> = z.object({
  id: z.int().optional(),
  priority: z.int().optional(),
  segment: z.int(),
  uuid: z.string().optional(),
});
