/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomCreateSegmentOverrideFeatureSegmentInput,
  CustomCreateSegmentOverrideFeatureSegmentInput$zodSchema,
} from "./customcreatesegmentoverridefeaturesegmentinput.js";
import {
  FeatureStateValue2,
  FeatureStateValue2$zodSchema,
} from "./featurestatevalue2.js";
import {
  MultivariateFeatureStateValueInput2,
  MultivariateFeatureStateValueInput2$zodSchema,
} from "./multivariatefeaturestatevalueinput2.js";

/**
 * Adds nested create feature
 */
export type CustomEnvironmentFeatureVersionFeatureStateInput = {
  enabled?: boolean | undefined;
  feature_state_value: FeatureStateValue2;
  feature_segment?:
    | CustomCreateSegmentOverrideFeatureSegmentInput
    | null
    | undefined;
  multivariate_feature_state_values?:
    | Array<MultivariateFeatureStateValueInput2>
    | undefined;
};

export const CustomEnvironmentFeatureVersionFeatureStateInput$zodSchema:
  z.ZodType<CustomEnvironmentFeatureVersionFeatureStateInput> = z.object({
    enabled: z.boolean().optional(),
    feature_segment: CustomCreateSegmentOverrideFeatureSegmentInput$zodSchema
      .nullable().optional(),
    feature_state_value: FeatureStateValue2$zodSchema,
    multivariate_feature_state_values: z.array(
      MultivariateFeatureStateValueInput2$zodSchema,
    ).optional(),
  }).describe("Adds nested create feature");
