/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomCreateSegmentOverrideFeatureSegment,
  CustomCreateSegmentOverrideFeatureSegment$zodSchema,
} from "./customcreatesegmentoverridefeaturesegment.js";
import {
  FeatureStateValue2,
  FeatureStateValue2$zodSchema,
} from "./featurestatevalue2.js";
import {
  MultivariateFeatureStateValue2,
  MultivariateFeatureStateValue2$zodSchema,
} from "./multivariatefeaturestatevalue2.js";

/**
 * Adds nested create feature
 */
export type CustomEnvironmentFeatureVersionFeatureState = {
  id?: number | undefined;
  feature?: number | undefined;
  enabled?: boolean | undefined;
  feature_state_value: FeatureStateValue2;
  feature_segment?:
    | CustomCreateSegmentOverrideFeatureSegment
    | null
    | undefined;
  deleted_at?: string | null | undefined;
  uuid?: string | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  live_from?: string | null | undefined;
  environment?: number | null | undefined;
  identity?: number | null | undefined;
  change_request?: number | null | undefined;
  multivariate_feature_state_values?:
    | Array<MultivariateFeatureStateValue2>
    | undefined;
};

export const CustomEnvironmentFeatureVersionFeatureState$zodSchema: z.ZodType<
  CustomEnvironmentFeatureVersionFeatureState
> = z.object({
  change_request: z.int().nullable().optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  deleted_at: z.iso.datetime({ offset: true }).nullable().optional(),
  enabled: z.boolean().optional(),
  environment: z.int().nullable().optional(),
  feature: z.int().optional(),
  feature_segment: CustomCreateSegmentOverrideFeatureSegment$zodSchema
    .nullable().optional(),
  feature_state_value: FeatureStateValue2$zodSchema,
  id: z.int().optional(),
  identity: z.int().nullable().optional(),
  live_from: z.iso.datetime({ offset: true }).nullable().optional(),
  multivariate_feature_state_values: z.array(
    MultivariateFeatureStateValue2$zodSchema,
  ).optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  uuid: z.string().optional(),
}).describe("Adds nested create feature");
