/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CustomCreateSegmentOverrideFeatureSegmentInput = {
  segment: number;
  priority?: number | undefined;
};

export const CustomCreateSegmentOverrideFeatureSegmentInput$zodSchema:
  z.ZodType<CustomCreateSegmentOverrideFeatureSegmentInput> = z.object({
    priority: z.int().optional(),
    segment: z.int(),
  });
