/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `NOT_STARTED` - Not Started
 *
 * @remarks
 * * `IN_PROGRESS` - In Progress
 * * `COMPLETE` - Complete
 * * `INCOMPLETE` - Incomplete (identity overrides skipped)
 */
export const EdgeV2MigrationStatusEnum = {
  NotStarted: "NOT_STARTED",
  InProgress: "IN_PROGRESS",
  Complete: "COMPLETE",
  Incomplete: "INCOMPLETE",
} as const;
/**
 * * `NOT_STARTED` - Not Started
 *
 * @remarks
 * * `IN_PROGRESS` - In Progress
 * * `COMPLETE` - Complete
 * * `INCOMPLETE` - Incomplete (identity overrides skipped)
 */
export type EdgeV2MigrationStatusEnum = ClosedEnum<
  typeof EdgeV2MigrationStatusEnum
>;

export const EdgeV2MigrationStatusEnum$zodSchema = z.enum([
  "NOT_STARTED",
  "IN_PROGRESS",
  "COMPLETE",
  "INCOMPLETE",
]).describe(
  "* `NOT_STARTED` - Not Started\n* `IN_PROGRESS` - In Progress\n* `COMPLETE` - Complete\n* `INCOMPLETE` - Incomplete (identity overrides skipped)",
);
