/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EnvironmentFeatureVersion = {
  created_at?: string | undefined;
  updated_at?: string | undefined;
  published?: boolean | undefined;
  live_from?: string | null | undefined;
  uuid?: string | undefined;
  is_live?: boolean | undefined;
  published_by?: number | null | undefined;
  created_by?: number | null | undefined;
  description?: string | null | undefined;
};

export const EnvironmentFeatureVersion$zodSchema: z.ZodType<
  EnvironmentFeatureVersion
> = z.object({
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.int().nullable().optional(),
  description: z.string().nullable().optional(),
  is_live: z.boolean().optional(),
  live_from: z.iso.datetime({ offset: true }).nullable().optional(),
  published: z.boolean().optional(),
  published_by: z.int().nullable().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  uuid: z.string().optional(),
});
