/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Metadata, Metadata$zodSchema } from "./metadata.js";

/**
 * Functionality for serializers that need to handle metadata
 */
export type EnvironmentSerializerWithMetadata = {
  id?: number | undefined;
  uuid?: string | undefined;
  name: string;
  api_key?: string | undefined;
  description?: string | null | undefined;
  project: number;
  minimum_change_request_approvals?: number | null | undefined;
  allow_client_traits?: boolean | undefined;
  banner_text?: string | null | undefined;
  banner_colour?: string | null | undefined;
  hide_disabled_flags?: boolean | null | undefined;
  use_mv_v2_evaluation?: boolean | undefined;
  use_identity_composite_key_for_hashing?: boolean | undefined;
  hide_sensitive_data?: boolean | undefined;
  use_v2_feature_versioning?: boolean | undefined;
  use_identity_overrides_in_local_eval?: boolean | undefined;
  is_creating?: boolean | undefined;
  metadata?: Array<Metadata> | undefined;
};

export const EnvironmentSerializerWithMetadata$zodSchema: z.ZodType<
  EnvironmentSerializerWithMetadata
> = z.object({
  allow_client_traits: z.boolean().optional(),
  api_key: z.string().optional(),
  banner_colour: z.string().nullable().optional(),
  banner_text: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  hide_disabled_flags: z.boolean().nullable().optional(),
  hide_sensitive_data: z.boolean().optional(),
  id: z.int().optional(),
  is_creating: z.boolean().optional(),
  metadata: z.array(Metadata$zodSchema).optional(),
  minimum_change_request_approvals: z.int().nullable().optional(),
  name: z.string(),
  project: z.int(),
  use_identity_composite_key_for_hashing: z.boolean().optional(),
  use_identity_overrides_in_local_eval: z.boolean().optional(),
  use_mv_v2_evaluation: z.boolean().optional(),
  use_v2_feature_versioning: z.boolean().optional(),
  uuid: z.string().optional(),
}).describe("Functionality for serializers that need to handle metadata");
