/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomEnvironmentFeatureVersionFeatureStateInput,
  CustomEnvironmentFeatureVersionFeatureStateInput$zodSchema,
} from "./customenvironmentfeatureversionfeaturestateinput.js";

export type EnvironmentFeatureVersionCreateInput = {
  live_from?: string | null | undefined;
  description?: string | null | undefined;
  feature_states_to_create?:
    | Array<CustomEnvironmentFeatureVersionFeatureStateInput>
    | null
    | undefined;
  feature_states_to_update?:
    | Array<CustomEnvironmentFeatureVersionFeatureStateInput>
    | null
    | undefined;
  segment_ids_to_delete_overrides?: Array<number> | null | undefined;
  publish_immediately?: boolean | undefined;
};

export const EnvironmentFeatureVersionCreateInput$zodSchema: z.ZodType<
  EnvironmentFeatureVersionCreateInput
> = z.object({
  description: z.string().nullable().optional(),
  feature_states_to_create: z.array(
    CustomEnvironmentFeatureVersionFeatureStateInput$zodSchema,
  ).nullable().optional(),
  feature_states_to_update: z.array(
    CustomEnvironmentFeatureVersionFeatureStateInput$zodSchema,
  ).nullable().optional(),
  live_from: z.iso.datetime({ offset: true }).nullable().optional(),
  publish_immediately: z.boolean().default(false),
  segment_ids_to_delete_overrides: z.array(z.int()).nullable().optional(),
});
