/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BlankEnum, BlankEnum$zodSchema } from "./blankenum.js";
import { Type975Enum, Type975Enum$zodSchema } from "./type975enum.js";

export type FeatureStateValueType2 = Type975Enum | BlankEnum;

export const FeatureStateValueType2$zodSchema: z.ZodType<
  FeatureStateValueType2
> = z.union([
  Type975Enum$zodSchema,
  BlankEnum$zodSchema,
]);

export type FeatureStateValue2 = {
  type?: Type975Enum | BlankEnum | null | undefined;
  string_value?: string | null | undefined;
  integer_value?: number | null | undefined;
  boolean_value?: boolean | null | undefined;
};

export const FeatureStateValue2$zodSchema: z.ZodType<FeatureStateValue2> = z
  .object({
    boolean_value: z.boolean().nullable().optional(),
    integer_value: z.int().nullable().optional(),
    string_value: z.string().nullable().optional(),
    type: z.union([
      Type975Enum$zodSchema,
      BlankEnum$zodSchema,
    ]).nullable().optional(),
  });
