/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  FeatureHealthEventReason,
  FeatureHealthEventReason$zodSchema,
} from "./featurehealtheventreason.js";

/**
 * * `UNHEALTHY` - Unhealthy
 *
 * @remarks
 * * `HEALTHY` - Healthy
 */
export const FeatureHealthEventType = {
  Unhealthy: "UNHEALTHY",
  Healthy: "HEALTHY",
} as const;
/**
 * * `UNHEALTHY` - Unhealthy
 *
 * @remarks
 * * `HEALTHY` - Healthy
 */
export type FeatureHealthEventType = ClosedEnum<typeof FeatureHealthEventType>;

export const FeatureHealthEventType$zodSchema = z.enum([
  "UNHEALTHY",
  "HEALTHY",
]).describe("* `UNHEALTHY` - Unhealthy\n* `HEALTHY` - Healthy");

export type FeatureHealthEvent = {
  id?: number | undefined;
  created_at?: string | undefined;
  environment?: number | null | undefined;
  feature?: number | undefined;
  provider_name?: string | null | undefined;
  reason: FeatureHealthEventReason | null;
  type?: FeatureHealthEventType | undefined;
};

export const FeatureHealthEvent$zodSchema: z.ZodType<FeatureHealthEvent> = z
  .object({
    created_at: z.iso.datetime({ offset: true }).optional(),
    environment: z.int().nullable().optional(),
    feature: z.int().optional(),
    id: z.int().optional(),
    provider_name: z.string().nullable().optional(),
    reason: FeatureHealthEventReason$zodSchema.nullable(),
    type: FeatureHealthEventType$zodSchema.optional(),
  });
