/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CodeReferenceDetail,
  CodeReferenceDetail$zodSchema,
} from "./codereferencedetail.js";
import {
  VcsProviderEnum,
  VcsProviderEnum$zodSchema,
} from "./vcsproviderenum.js";

export type FeatureFlagCodeReferencesRepositorySummary = {
  repository_url: string;
  vcs_provider: VcsProviderEnum;
  revision: string;
  last_successful_repository_scanned_at: string;
  last_feature_found_at: string | null;
  code_references: Array<CodeReferenceDetail>;
};

export const FeatureFlagCodeReferencesRepositorySummary$zodSchema: z.ZodType<
  FeatureFlagCodeReferencesRepositorySummary
> = z.object({
  code_references: z.array(CodeReferenceDetail$zodSchema),
  last_feature_found_at: z.iso.datetime({ offset: true }).nullable(),
  last_successful_repository_scanned_at: z.iso.datetime({ offset: true }),
  repository_url: z.string(),
  revision: z.string(),
  vcs_provider: VcsProviderEnum$zodSchema,
});
