/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FeatureHealthEventReasonUrlBlock = {
  url: string;
  title?: string | undefined;
};

export const FeatureHealthEventReasonUrlBlock$zodSchema: z.ZodType<
  FeatureHealthEventReasonUrlBlock
> = z.object({
  title: z.string().optional(),
  url: z.string(),
});
