/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FeatureHealthEventReasonTextBlock,
  FeatureHealthEventReasonTextBlock$zodSchema,
} from "./featurehealtheventreasontextblock.js";
import {
  FeatureHealthEventReasonUrlBlock,
  FeatureHealthEventReasonUrlBlock$zodSchema,
} from "./featurehealtheventreasonurlblock.js";

export type FeatureHealthEventReason = {
  text_blocks: Array<FeatureHealthEventReasonTextBlock>;
  url_blocks: Array<FeatureHealthEventReasonUrlBlock>;
};

export const FeatureHealthEventReason$zodSchema: z.ZodType<
  FeatureHealthEventReason
> = z.object({
  text_blocks: z.array(FeatureHealthEventReasonTextBlock$zodSchema),
  url_blocks: z.array(FeatureHealthEventReasonUrlBlock$zodSchema),
});
