/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FeatureFlagCodeReferencesRepositoryCount = {
  repository_url: string;
  count: number;
  last_successful_repository_scanned_at: string;
  last_feature_found_at: string | null;
};

export const FeatureFlagCodeReferencesRepositoryCount$zodSchema: z.ZodType<
  FeatureFlagCodeReferencesRepositoryCount
> = z.object({
  count: z.int(),
  last_feature_found_at: z.iso.datetime({ offset: true }).nullable(),
  last_successful_repository_scanned_at: z.iso.datetime({ offset: true }),
  repository_url: z.string(),
});
