/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `GITHUB_ISSUE` - GitHub Issue
 *
 * @remarks
 * * `GITHUB_PR` - GitHub PR
 */
export const FeatureExternalResourceTypeEnum = {
  GithubIssue: "GITHUB_ISSUE",
  GithubPr: "GITHUB_PR",
} as const;
/**
 * * `GITHUB_ISSUE` - GitHub Issue
 *
 * @remarks
 * * `GITHUB_PR` - GitHub PR
 */
export type FeatureExternalResourceTypeEnum = ClosedEnum<
  typeof FeatureExternalResourceTypeEnum
>;

export const FeatureExternalResourceTypeEnum$zodSchema = z.enum([
  "GITHUB_ISSUE",
  "GITHUB_PR",
]).describe("* `GITHUB_ISSUE` - GitHub Issue\n* `GITHUB_PR` - GitHub PR");
