/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FeatureExternalResourceTypeEnum,
  FeatureExternalResourceTypeEnum$zodSchema,
} from "./featureexternalresourcetypeenum.js";

export type FeatureExternalResource = {
  id?: number | undefined;
  url: string;
  type: FeatureExternalResourceTypeEnum;
  metadata?: any | null | undefined;
  feature: number;
};

export const FeatureExternalResource$zodSchema: z.ZodType<
  FeatureExternalResource
> = z.object({
  feature: z.int(),
  id: z.int().optional(),
  metadata: z.any().nullable().optional(),
  type: FeatureExternalResourceTypeEnum$zodSchema,
  url: z.string(),
});
