/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FeatureHealthEventReasonTextBlock = {
  text: string;
  title?: string | undefined;
};

export const FeatureHealthEventReasonTextBlock$zodSchema: z.ZodType<
  FeatureHealthEventReasonTextBlock
> = z.object({
  text: z.string(),
  title: z.string().optional(),
});
