/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Labels, Labels$zodSchema } from "./labels.js";

export type FeatureEvaluationData = {
  day: string;
  count: number;
  labels: Labels | null;
};

export const FeatureEvaluationData$zodSchema: z.ZodType<FeatureEvaluationData> =
  z.object({
    count: z.int(),
    day: z.string(),
    labels: Labels$zodSchema.nullable(),
  });
