/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { UserList, UserList$zodSchema } from "./userlist.js";

export type InviteList = {
  id?: number | undefined;
  email: string;
  date_created?: string | undefined;
  invited_by: UserList;
  permission_groups?: Array<number> | undefined;
};

export const InviteList$zodSchema: z.ZodType<InviteList> = z.object({
  date_created: z.iso.datetime({ offset: true }).optional(),
  email: z.string(),
  id: z.int().optional(),
  invited_by: UserList$zodSchema,
  permission_groups: z.array(z.int()).optional(),
});
