/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RoleEnum, RoleEnum$zodSchema } from "./roleenum.js";

export type Invite = {
  id?: number | undefined;
  email: string;
  role?: RoleEnum | undefined;
  date_created?: string | undefined;
  permission_groups?: Array<number | null> | undefined;
};

export const Invite$zodSchema: z.ZodType<Invite> = z.object({
  date_created: z.iso.datetime({ offset: true }).optional(),
  email: z.string(),
  id: z.int().optional(),
  permission_groups: z.array(z.int().nullable()).optional(),
  role: RoleEnum$zodSchema.optional(),
});
