/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RoleEnum, RoleEnum$zodSchema } from "./roleenum.js";

export type InviteInput = {
  email: string;
  role?: RoleEnum | undefined;
  permission_groups?: Array<number | null> | undefined;
};

export const InviteInput$zodSchema: z.ZodType<InviteInput> = z.object({
  email: z.string(),
  permission_groups: z.array(z.int().nullable()).optional(),
  role: RoleEnum$zodSchema.optional(),
});
