/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Labels = {
  client_application_name?: string | null | undefined;
  client_application_version?: string | null | undefined;
  user_agent?: string | null | undefined;
};

export const Labels$zodSchema: z.ZodType<Labels> = z.object({
  client_application_name: z.string().nullable().optional(),
  client_application_version: z.string().nullable().optional(),
  user_agent: z.string().nullable().optional(),
});
