/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  FeatureFlagCodeReferencesRepositoryCount,
  FeatureFlagCodeReferencesRepositoryCount$zodSchema,
} from "./featureflagcodereferencesrepositorycount.js";
import { Metadata, Metadata$zodSchema } from "./metadata.js";
import {
  NestedMultivariateFeatureOption,
  NestedMultivariateFeatureOption$zodSchema,
} from "./nestedmultivariatefeatureoption.js";
import { UserList, UserList$zodSchema } from "./userlist.js";
import {
  UserPermissionGroupSummary,
  UserPermissionGroupSummary$zodSchema,
} from "./userpermissiongroupsummary.js";

/**
 * * `STANDARD` - STANDARD
 *
 * @remarks
 * * `MULTIVARIATE` - MULTIVARIATE
 */
export const ListFeatureType = {
  Standard: "STANDARD",
  Multivariate: "MULTIVARIATE",
} as const;
/**
 * * `STANDARD` - STANDARD
 *
 * @remarks
 * * `MULTIVARIATE` - MULTIVARIATE
 */
export type ListFeatureType = ClosedEnum<typeof ListFeatureType>;

export const ListFeatureType$zodSchema = z.enum([
  "STANDARD",
  "MULTIVARIATE",
]).describe("* `STANDARD` - STANDARD\n* `MULTIVARIATE` - MULTIVARIATE");

export type ListFeatureEnvironmentFeatureStateFeatureStateValue =
  | string
  | number
  | boolean;

export const ListFeatureEnvironmentFeatureStateFeatureStateValue$zodSchema:
  z.ZodType<ListFeatureEnvironmentFeatureStateFeatureStateValue> = z.union([
    z.string(),
    z.int(),
    z.boolean(),
  ]);

export type ListFeatureEnvironmentFeatureStateFeatureStateSerializerSmall = {
  id?: number | undefined;
  feature_state_value?: string | number | boolean | null | undefined;
  environment?: number | null | undefined;
  identity?: number | null | undefined;
  feature_segment?: number | null | undefined;
  enabled?: boolean | undefined;
};

export const ListFeatureEnvironmentFeatureStateFeatureStateSerializerSmall$zodSchema:
  z.ZodType<ListFeatureEnvironmentFeatureStateFeatureStateSerializerSmall> = z
    .object({
      enabled: z.boolean().optional(),
      environment: z.int().nullable().optional(),
      feature_segment: z.int().nullable().optional(),
      feature_state_value: z.union([
        z.string(),
        z.int(),
        z.boolean(),
      ]).nullable().optional(),
      id: z.int().optional(),
      identity: z.int().nullable().optional(),
    });

export type ListFeatureSegmentFeatureStateFeatureStateValue =
  | string
  | number
  | boolean;

export const ListFeatureSegmentFeatureStateFeatureStateValue$zodSchema:
  z.ZodType<ListFeatureSegmentFeatureStateFeatureStateValue> = z.union([
    z.string(),
    z.int(),
    z.boolean(),
  ]);

export type ListFeatureSegmentFeatureStateFeatureStateSerializerSmall = {
  id?: number | undefined;
  feature_state_value?: string | number | boolean | null | undefined;
  environment?: number | null | undefined;
  identity?: number | null | undefined;
  feature_segment?: number | null | undefined;
  enabled?: boolean | undefined;
};

export const ListFeatureSegmentFeatureStateFeatureStateSerializerSmall$zodSchema:
  z.ZodType<ListFeatureSegmentFeatureStateFeatureStateSerializerSmall> = z
    .object({
      enabled: z.boolean().optional(),
      environment: z.int().nullable().optional(),
      feature_segment: z.int().nullable().optional(),
      feature_state_value: z.union([
        z.string(),
        z.int(),
        z.boolean(),
      ]).nullable().optional(),
      id: z.int().optional(),
      identity: z.int().nullable().optional(),
    });

/**
 * Functionality for serializers that need to handle metadata
 */
export type ListFeature = {
  id?: number | undefined;
  name: string;
  type?: ListFeatureType | undefined;
  default_enabled?: boolean | undefined;
  initial_value?: string | null | undefined;
  created_date?: string | undefined;
  description?: string | null | undefined;
  tags?: Array<number> | undefined;
  multivariate_options?: Array<NestedMultivariateFeatureOption> | undefined;
  is_archived?: boolean | undefined;
  owners?: Array<UserList> | undefined;
  group_owners?: Array<UserPermissionGroupSummary> | undefined;
  uuid?: string | undefined;
  project?: number | undefined;
  environment_feature_state?:
    | ListFeatureEnvironmentFeatureStateFeatureStateSerializerSmall
    | null
    | undefined;
  segment_feature_state?:
    | ListFeatureSegmentFeatureStateFeatureStateSerializerSmall
    | null
    | undefined;
  num_segment_overrides?: number | undefined;
  num_identity_overrides?: number | null | undefined;
  is_num_identity_overrides_complete?: boolean | undefined;
  is_server_key_only?: boolean | undefined;
  last_modified_in_any_environment?: string | null | undefined;
  last_modified_in_current_environment?: string | null | undefined;
  metadata?: Array<Metadata> | undefined;
  code_references_counts?:
    | Array<FeatureFlagCodeReferencesRepositoryCount>
    | undefined;
};

export const ListFeature$zodSchema: z.ZodType<ListFeature> = z.object({
  code_references_counts: z.array(
    FeatureFlagCodeReferencesRepositoryCount$zodSchema,
  ).optional(),
  created_date: z.iso.datetime({ offset: true }).optional(),
  default_enabled: z.boolean().optional(),
  description: z.string().nullable().optional(),
  environment_feature_state: z.lazy(() =>
    ListFeatureEnvironmentFeatureStateFeatureStateSerializerSmall$zodSchema
  ).nullable().optional(),
  group_owners: z.array(UserPermissionGroupSummary$zodSchema).optional(),
  id: z.int().optional(),
  initial_value: z.string().nullable().optional(),
  is_archived: z.boolean().optional(),
  is_num_identity_overrides_complete: z.boolean().default(true),
  is_server_key_only: z.boolean().optional(),
  last_modified_in_any_environment: z.iso.datetime({ offset: true }).nullable()
    .optional(),
  last_modified_in_current_environment: z.iso.datetime({ offset: true })
    .nullable().optional(),
  metadata: z.array(Metadata$zodSchema).optional(),
  multivariate_options: z.array(NestedMultivariateFeatureOption$zodSchema)
    .optional(),
  name: z.string(),
  num_identity_overrides: z.int().nullable().optional(),
  num_segment_overrides: z.int().optional(),
  owners: z.array(UserList$zodSchema).optional(),
  project: z.int().optional(),
  segment_feature_state: z.lazy(() =>
    ListFeatureSegmentFeatureStateFeatureStateSerializerSmall$zodSchema
  ).nullable().optional(),
  tags: z.array(z.int()).optional(),
  type: ListFeatureType$zodSchema.optional(),
  uuid: z.string().optional(),
}).describe("Functionality for serializers that need to handle metadata");
