/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ListUserPermissionGroupMembership,
  ListUserPermissionGroupMembership$zodSchema,
} from "./listuserpermissiongroupmembership.js";

export type ListUserPermissionGroup = {
  id?: number | undefined;
  name: string;
  users?: Array<ListUserPermissionGroupMembership> | undefined;
  is_default?: boolean | undefined;
  external_id?: string | null | undefined;
};

export const ListUserPermissionGroup$zodSchema: z.ZodType<
  ListUserPermissionGroup
> = z.object({
  external_id: z.string().nullable().optional(),
  id: z.int().optional(),
  is_default: z.boolean().optional(),
  name: z.string(),
  users: z.array(ListUserPermissionGroupMembership$zodSchema).optional(),
});
