/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { MetadataInput, MetadataInput$zodSchema } from "./metadatainput.js";
import {
  NestedMultivariateFeatureOptionInput,
  NestedMultivariateFeatureOptionInput$zodSchema,
} from "./nestedmultivariatefeatureoption.js";

/**
 * Functionality for serializers that need to handle metadata
 */
export type ListFeatureInput = {
  name: string;
  default_enabled?: boolean | undefined;
  initial_value?: string | null | undefined;
  description?: string | null | undefined;
  tags?: Array<number> | undefined;
  multivariate_options?:
    | Array<NestedMultivariateFeatureOptionInput>
    | undefined;
  is_archived?: boolean | undefined;
  is_server_key_only?: boolean | undefined;
  metadata?: Array<MetadataInput> | undefined;
};

export const ListFeatureInput$zodSchema: z.ZodType<ListFeatureInput> = z.object(
  {
    default_enabled: z.boolean().optional(),
    description: z.string().nullable().optional(),
    initial_value: z.string().nullable().optional(),
    is_archived: z.boolean().optional(),
    is_server_key_only: z.boolean().optional(),
    metadata: z.array(MetadataInput$zodSchema).optional(),
    multivariate_options: z.array(
      NestedMultivariateFeatureOptionInput$zodSchema,
    ).optional(),
    name: z.string(),
    tags: z.array(z.int()).optional(),
  },
).describe("Functionality for serializers that need to handle metadata");
