/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ListUserPermissionGroupMembership = {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  last_login: string;
  group_admin?: boolean | undefined;
};

export const ListUserPermissionGroupMembership$zodSchema: z.ZodType<
  ListUserPermissionGroupMembership
> = z.object({
  email: z.string(),
  first_name: z.string(),
  group_admin: z.boolean().optional(),
  id: z.int(),
  last_login: z.string(),
  last_name: z.string(),
});
