/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Metadata = {
  id?: number | undefined;
  model_field: number;
  field_value: string;
};

export const Metadata$zodSchema: z.ZodType<Metadata> = z.object({
  field_value: z.string(),
  id: z.int().optional(),
  model_field: z.int(),
});
