/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MetadataInput = { model_field: number; field_value: string };

export const MetadataInput$zodSchema: z.ZodType<MetadataInput> = z.object({
  field_value: z.string(),
  model_field: z.int(),
});
