/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MultivariateFeatureStateValue1 = {
  id?: number | undefined;
  multivariate_feature_option: number;
  percentage_allocation: number;
};

export const MultivariateFeatureStateValue1$zodSchema: z.ZodType<
  MultivariateFeatureStateValue1
> = z.object({
  id: z.int().optional(),
  multivariate_feature_option: z.int(),
  percentage_allocation: z.number(),
});
