/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MultivariateFeatureStateValueInput1 = {
  multivariate_feature_option: number;
  percentage_allocation: number;
};

export const MultivariateFeatureStateValueInput1$zodSchema: z.ZodType<
  MultivariateFeatureStateValueInput1
> = z.object({
  multivariate_feature_option: z.int(),
  percentage_allocation: z.number(),
});
