/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConditionOutput,
  ConditionOutput$zodSchema,
} from "./conditionoutput.js";
import {
  SegmentRuleTypeEnum,
  SegmentRuleTypeEnum$zodSchema,
} from "./segmentruletypeenum.js";

/**
 * Adds nested create feature
 */
export type NestedSegmentRuleOutput = {
  id?: number | undefined;
  type: SegmentRuleTypeEnum;
  conditions?: Array<ConditionOutput> | undefined;
};

export const NestedSegmentRuleOutput$zodSchema: z.ZodType<
  NestedSegmentRuleOutput
> = z.object({
  conditions: z.array(ConditionOutput$zodSchema).optional(),
  id: z.int().optional(),
  type: SegmentRuleTypeEnum$zodSchema,
}).describe("Adds nested create feature");
