/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ConditionInput, ConditionInput$zodSchema } from "./conditioninput.js";
import {
  SegmentRuleTypeEnum,
  SegmentRuleTypeEnum$zodSchema,
} from "./segmentruletypeenum.js";

/**
 * Adds nested create feature
 */
export type NestedSegmentRuleInput = {
  type: SegmentRuleTypeEnum;
  conditions?: Array<ConditionInput> | undefined;
  delete?: boolean | undefined;
};

export const NestedSegmentRuleInput$zodSchema: z.ZodType<
  NestedSegmentRuleInput
> = z.object({
  conditions: z.array(ConditionInput$zodSchema).optional(),
  delete: z.boolean().optional(),
  type: SegmentRuleTypeEnum$zodSchema,
}).describe("Adds nested create feature");
