/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BlankEnum, BlankEnum$zodSchema } from "./blankenum.js";
import { Type975Enum, Type975Enum$zodSchema } from "./type975enum.js";

export type NestedMultivariateFeatureOptionType = Type975Enum | BlankEnum;

export const NestedMultivariateFeatureOptionType$zodSchema: z.ZodType<
  NestedMultivariateFeatureOptionType
> = z.union([
  Type975Enum$zodSchema,
  BlankEnum$zodSchema,
]);

export type NestedMultivariateFeatureOption = {
  id?: number | undefined;
  uuid?: string | undefined;
  type?: Type975Enum | BlankEnum | null | undefined;
  integer_value?: number | null | undefined;
  string_value?: string | null | undefined;
  boolean_value?: boolean | null | undefined;
  default_percentage_allocation?: number | undefined;
};

export const NestedMultivariateFeatureOption$zodSchema: z.ZodType<
  NestedMultivariateFeatureOption
> = z.object({
  boolean_value: z.boolean().nullable().optional(),
  default_percentage_allocation: z.number().optional(),
  id: z.int().optional(),
  integer_value: z.int().nullable().optional(),
  string_value: z.string().nullable().optional(),
  type: z.union([
    Type975Enum$zodSchema,
    BlankEnum$zodSchema,
  ]).nullable().optional(),
  uuid: z.string().optional(),
});

export type NestedMultivariateFeatureOptionInput = {
  type?: Type975Enum | BlankEnum | null | undefined;
  integer_value?: number | null | undefined;
  string_value?: string | null | undefined;
  boolean_value?: boolean | null | undefined;
  default_percentage_allocation?: number | undefined;
};

export const NestedMultivariateFeatureOptionInput$zodSchema: z.ZodType<
  NestedMultivariateFeatureOptionInput
> = z.object({
  boolean_value: z.boolean().nullable().optional(),
  default_percentage_allocation: z.number().optional(),
  integer_value: z.int().nullable().optional(),
  string_value: z.string().nullable().optional(),
  type: z.union([
    Type975Enum$zodSchema,
    BlankEnum$zodSchema,
  ]).nullable().optional(),
});
