/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Subscription, Subscription$zodSchema } from "./subscription.js";

export type OrganisationSerializerFull = {
  id?: number | undefined;
  uuid?: string | undefined;
  name: string;
  created_date?: string | undefined;
  webhook_notification_email?: string | null | undefined;
  num_seats?: number | undefined;
  subscription?: Subscription | undefined;
  role?: string | null | undefined;
  persist_trait_data?: boolean | undefined;
  block_access_to_admin?: boolean | undefined;
  restrict_project_create_to_admin?: boolean | undefined;
  force_2fa?: boolean | undefined;
};

export const OrganisationSerializerFull$zodSchema: z.ZodType<
  OrganisationSerializerFull
> = z.object({
  block_access_to_admin: z.boolean().optional(),
  created_date: z.iso.datetime({ offset: true }).optional(),
  force_2fa: z.boolean().optional(),
  id: z.int().optional(),
  name: z.string(),
  num_seats: z.int().optional(),
  persist_trait_data: z.boolean().optional(),
  restrict_project_create_to_admin: z.boolean().optional(),
  role: z.string().nullable().optional(),
  subscription: Subscription$zodSchema.optional(),
  uuid: z.string().optional(),
  webhook_notification_email: z.string().nullable().optional(),
});
