/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ListUserPermissionGroup,
  ListUserPermissionGroup$zodSchema,
} from "./listuserpermissiongroup.js";

export type PaginatedListUserPermissionGroupList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<ListUserPermissionGroup>;
};

export const PaginatedListUserPermissionGroupList$zodSchema: z.ZodType<
  PaginatedListUserPermissionGroupList
> = z.object({
  count: z.int(),
  next: z.string().nullable().optional(),
  previous: z.string().nullable().optional(),
  results: z.array(ListUserPermissionGroup$zodSchema),
});
