/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Role, Role$zodSchema } from "./role.js";

export type PaginatedRoleList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<Role>;
};

export const PaginatedRoleList$zodSchema: z.ZodType<PaginatedRoleList> = z
  .object({
    count: z.int(),
    next: z.string().nullable().optional(),
    previous: z.string().nullable().optional(),
    results: z.array(Role$zodSchema),
  });
