/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MultivariateFeatureOption,
  MultivariateFeatureOption$zodSchema,
} from "./multivariatefeatureoption.js";

export type PaginatedMultivariateFeatureOptionList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<MultivariateFeatureOption>;
};

export const PaginatedMultivariateFeatureOptionList$zodSchema: z.ZodType<
  PaginatedMultivariateFeatureOptionList
> = z.object({
  count: z.int(),
  next: z.string().nullable().optional(),
  previous: z.string().nullable().optional(),
  results: z.array(MultivariateFeatureOption$zodSchema),
});
