/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ProjectChangeRequestList,
  ProjectChangeRequestList$zodSchema,
} from "./projectchangerequestlist.js";

export type PaginatedProjectChangeRequestListList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<ProjectChangeRequestList>;
};

export const PaginatedProjectChangeRequestListList$zodSchema: z.ZodType<
  PaginatedProjectChangeRequestListList
> = z.object({
  count: z.int(),
  next: z.string().nullable().optional(),
  previous: z.string().nullable().optional(),
  results: z.array(ProjectChangeRequestList$zodSchema),
});
