/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  OrganisationSerializerFull,
  OrganisationSerializerFull$zodSchema,
} from "./organisationserializerfull.js";

export type PaginatedOrganisationSerializerFullList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<OrganisationSerializerFull>;
};

export const PaginatedOrganisationSerializerFullList$zodSchema: z.ZodType<
  PaginatedOrganisationSerializerFullList
> = z.object({
  count: z.int(),
  next: z.string().nullable().optional(),
  previous: z.string().nullable().optional(),
  results: z.array(OrganisationSerializerFull$zodSchema),
});
