/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EnvironmentSerializerWithMetadata,
  EnvironmentSerializerWithMetadata$zodSchema,
} from "./environmentserializerwithmetadata.js";

export type PaginatedEnvironmentSerializerWithMetadataList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<EnvironmentSerializerWithMetadata>;
};

export const PaginatedEnvironmentSerializerWithMetadataList$zodSchema:
  z.ZodType<PaginatedEnvironmentSerializerWithMetadataList> = z.object({
    count: z.int(),
    next: z.string().nullable().optional(),
    previous: z.string().nullable().optional(),
    results: z.array(EnvironmentSerializerWithMetadata$zodSchema),
  });
