/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FeatureExternalResource,
  FeatureExternalResource$zodSchema,
} from "./featureexternalresource.js";

export type PaginatedFeatureExternalResourceList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<FeatureExternalResource>;
};

export const PaginatedFeatureExternalResourceList$zodSchema: z.ZodType<
  PaginatedFeatureExternalResourceList
> = z.object({
  count: z.int(),
  next: z.string().nullable().optional(),
  previous: z.string().nullable().optional(),
  results: z.array(FeatureExternalResource$zodSchema),
});
