/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ListFeature, ListFeature$zodSchema } from "./listfeature.js";

export type PaginatedListFeatureList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<ListFeature>;
};

export const PaginatedListFeatureList$zodSchema: z.ZodType<
  PaginatedListFeatureList
> = z.object({
  count: z.int(),
  next: z.string().nullable().optional(),
  previous: z.string().nullable().optional(),
  results: z.array(ListFeature$zodSchema),
});
