/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SegmentOutput, SegmentOutput$zodSchema } from "./segmentoutput.js";

export type PaginatedSegmentList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<SegmentOutput>;
};

export const PaginatedSegmentList$zodSchema: z.ZodType<PaginatedSegmentList> = z
  .object({
    count: z.int(),
    next: z.string().nullable().optional(),
    previous: z.string().nullable().optional(),
    results: z.array(SegmentOutput$zodSchema),
  });
