/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EnvironmentFeatureVersion,
  EnvironmentFeatureVersion$zodSchema,
} from "./environmentfeatureversion.js";

export type PaginatedEnvironmentFeatureVersionList = {
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
  results: Array<EnvironmentFeatureVersion>;
};

export const PaginatedEnvironmentFeatureVersionList$zodSchema: z.ZodType<
  PaginatedEnvironmentFeatureVersionList
> = z.object({
  count: z.int(),
  next: z.string().nullable().optional(),
  previous: z.string().nullable().optional(),
  results: z.array(EnvironmentFeatureVersion$zodSchema),
});
