/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `CHARGEBEE` - Chargebee
 *
 * @remarks
 * * `XERO` - Xero
 * * `AWS_MARKETPLACE` - AWS Marketplace
 */
export const PaymentMethodEnum = {
  Chargebee: "CHARGEBEE",
  Xero: "XERO",
  AwsMarketplace: "AWS_MARKETPLACE",
} as const;
/**
 * * `CHARGEBEE` - Chargebee
 *
 * @remarks
 * * `XERO` - Xero
 * * `AWS_MARKETPLACE` - AWS Marketplace
 */
export type PaymentMethodEnum = ClosedEnum<typeof PaymentMethodEnum>;

export const PaymentMethodEnum$zodSchema = z.enum([
  "CHARGEBEE",
  "XERO",
  "AWS_MARKETPLACE",
]).describe(
  "* `CHARGEBEE` - Chargebee\n* `XERO` - Xero\n* `AWS_MARKETPLACE` - AWS Marketplace",
);
