/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { StageAction, StageAction$zodSchema } from "./stageaction.js";
import { StageTrigger, StageTrigger$zodSchema } from "./stagetrigger.js";

/**
 * Adds nested create feature
 */
export type PipelineStage = {
  id?: number | undefined;
  name: string;
  pipeline?: number | undefined;
  environment: number;
  order: number;
  trigger: StageTrigger;
  actions: Array<StageAction>;
  features?: string | undefined;
};

export const PipelineStage$zodSchema: z.ZodType<PipelineStage> = z.object({
  actions: z.array(StageAction$zodSchema),
  environment: z.int(),
  features: z.string().optional(),
  id: z.int().optional(),
  name: z.string(),
  order: z.int(),
  pipeline: z.int().optional(),
  trigger: StageTrigger$zodSchema,
}).describe("Adds nested create feature");
