/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ProjectChangeRequestList = {
  id?: number | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  title?: string | undefined;
  description?: string | null | undefined;
  user?: number | null | undefined;
  committed_at?: string | null | undefined;
  committed_by?: number | null | undefined;
  deleted_at?: string | null | undefined;
  live_from?: string | null | undefined;
};

export const ProjectChangeRequestList$zodSchema: z.ZodType<
  ProjectChangeRequestList
> = z.object({
  committed_at: z.iso.datetime({ offset: true }).nullable().optional(),
  committed_by: z.int().nullable().optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  deleted_at: z.iso.datetime({ offset: true }).nullable().optional(),
  description: z.string().nullable().optional(),
  id: z.int().optional(),
  live_from: z.iso.datetime({ offset: true }).nullable().optional(),
  title: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  user: z.int().nullable().optional(),
});
