/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Mixin to add read only status to fields in a given serializer based on the existence
 *
 * @remarks
 * of a subscription and a black list of plan ids
 *
 * Example usage:
 *
 *     class MySerializer(ReadOnlyIfNotValidPlanMixin, ModelSerializer):
 *         class Meta:
 *             model = MyModel
 *             fields = ("my_field",)
 *
 *         invalid_plans = ("free",)
 *         field_names = ("my_field",)
 *
 *         def get_subscription(self):
 *             return subscription
 */
export type ProjectUpdateInput = {
  name: string;
  hide_disabled_flags?: boolean | undefined;
  prevent_flag_defaults?: boolean | undefined;
  only_allow_lower_case_feature_names?: boolean | undefined;
  feature_name_regex?: string | null | undefined;
  minimum_change_request_approvals?: number | null | undefined;
};

export const ProjectUpdateInput$zodSchema: z.ZodType<ProjectUpdateInput> = z
  .object({
    feature_name_regex: z.string().nullable().optional(),
    hide_disabled_flags: z.boolean().optional(),
    minimum_change_request_approvals: z.int().nullable().optional(),
    name: z.string(),
    only_allow_lower_case_feature_names: z.boolean().optional(),
    prevent_flag_defaults: z.boolean().optional(),
  }).describe(
    "Mixin to add read only status to fields in a given serializer based on the existence\nof a subscription and a black list of plan ids\n\nExample usage:\n\n    class MySerializer(ReadOnlyIfNotValidPlanMixin, ModelSerializer):\n        class Meta:\n            model = MyModel\n            fields = (\"my_field\",)\n\n        invalid_plans = (\"free\",)\n        field_names = (\"my_field\",)\n\n        def get_subscription(self):\n            return subscription",
  );
