/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * [Edge V2 migration] Project migration status. Set to `IN_PROGRESS` to trigger migration start.
 *
 * @remarks
 *
 * * `NOT_STARTED` - Not Started
 * * `IN_PROGRESS` - In Progress
 * * `COMPLETE` - Complete
 * * `INCOMPLETE` - Incomplete (identity overrides skipped)
 */
export const ProjectUpdateEdgeV2MigrationStatus = {
  NotStarted: "NOT_STARTED",
  InProgress: "IN_PROGRESS",
  Complete: "COMPLETE",
  Incomplete: "INCOMPLETE",
} as const;
/**
 * [Edge V2 migration] Project migration status. Set to `IN_PROGRESS` to trigger migration start.
 *
 * @remarks
 *
 * * `NOT_STARTED` - Not Started
 * * `IN_PROGRESS` - In Progress
 * * `COMPLETE` - Complete
 * * `INCOMPLETE` - Incomplete (identity overrides skipped)
 */
export type ProjectUpdateEdgeV2MigrationStatus = ClosedEnum<
  typeof ProjectUpdateEdgeV2MigrationStatus
>;

export const ProjectUpdateEdgeV2MigrationStatus$zodSchema = z.enum([
  "NOT_STARTED",
  "IN_PROGRESS",
  "COMPLETE",
  "INCOMPLETE",
]).describe(
  "[Edge V2 migration] Project migration status. Set to `IN_PROGRESS` to trigger migration start.\n\n* `NOT_STARTED` - Not Started\n* `IN_PROGRESS` - In Progress\n* `COMPLETE` - Complete\n* `INCOMPLETE` - Incomplete (identity overrides skipped)",
);

/**
 * Mixin to add read only status to fields in a given serializer based on the existence
 *
 * @remarks
 * of a subscription and a black list of plan ids
 *
 * Example usage:
 *
 *     class MySerializer(ReadOnlyIfNotValidPlanMixin, ModelSerializer):
 *         class Meta:
 *             model = MyModel
 *             fields = ("my_field",)
 *
 *         invalid_plans = ("free",)
 *         field_names = ("my_field",)
 *
 *         def get_subscription(self):
 *             return subscription
 */
export type ProjectUpdate = {
  id?: number | undefined;
  uuid?: string | undefined;
  name: string;
  organisation?: number | undefined;
  hide_disabled_flags?: boolean | undefined;
  enable_dynamo_db?: boolean | undefined;
  migration_status?: string | undefined;
  use_edge_identities?: boolean | undefined;
  prevent_flag_defaults?: boolean | undefined;
  enable_realtime_updates?: boolean | undefined;
  only_allow_lower_case_feature_names?: boolean | undefined;
  feature_name_regex?: string | null | undefined;
  show_edge_identity_overrides_for_feature?: boolean | undefined;
  stale_flags_limit_days?: number | undefined;
  edge_v2_migration_status?: ProjectUpdateEdgeV2MigrationStatus | undefined;
  minimum_change_request_approvals?: number | null | undefined;
};

export const ProjectUpdate$zodSchema: z.ZodType<ProjectUpdate> = z.object({
  edge_v2_migration_status: ProjectUpdateEdgeV2MigrationStatus$zodSchema
    .optional(),
  enable_dynamo_db: z.boolean().optional(),
  enable_realtime_updates: z.boolean().optional(),
  feature_name_regex: z.string().nullable().optional(),
  hide_disabled_flags: z.boolean().optional(),
  id: z.int().optional(),
  migration_status: z.string().optional(),
  minimum_change_request_approvals: z.int().nullable().optional(),
  name: z.string(),
  only_allow_lower_case_feature_names: z.boolean().optional(),
  organisation: z.int().optional(),
  prevent_flag_defaults: z.boolean().optional(),
  show_edge_identity_overrides_for_feature: z.boolean().optional(),
  stale_flags_limit_days: z.int().optional(),
  use_edge_identities: z.boolean().optional(),
  uuid: z.string().optional(),
}).describe(
  "Mixin to add read only status to fields in a given serializer based on the existence\nof a subscription and a black list of plan ids\n\nExample usage:\n\n    class MySerializer(ReadOnlyIfNotValidPlanMixin, ModelSerializer):\n        class Meta:\n            model = MyModel\n            fields = (\"my_field\",)\n\n        invalid_plans = (\"free\",)\n        field_names = (\"my_field\",)\n\n        def get_subscription(self):\n            return subscription",
);
