/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EdgeV2MigrationStatusEnum,
  EdgeV2MigrationStatusEnum$zodSchema,
} from "./edgev2migrationstatusenum.js";

export type ProjectRetrieve = {
  id?: number | undefined;
  uuid?: string | undefined;
  name: string;
  organisation: number;
  hide_disabled_flags?: boolean | undefined;
  enable_dynamo_db?: boolean | undefined;
  migration_status?: string | undefined;
  use_edge_identities?: boolean | undefined;
  prevent_flag_defaults?: boolean | undefined;
  enable_realtime_updates?: boolean | undefined;
  only_allow_lower_case_feature_names?: boolean | undefined;
  feature_name_regex?: string | null | undefined;
  show_edge_identity_overrides_for_feature?: boolean | undefined;
  stale_flags_limit_days?: number | undefined;
  edge_v2_migration_status?: EdgeV2MigrationStatusEnum | undefined;
  minimum_change_request_approvals?: number | null | undefined;
  max_segments_allowed?: number | undefined;
  max_features_allowed?: number | undefined;
  max_segment_overrides_allowed?: number | undefined;
  total_features?: number | undefined;
  total_segments?: number | undefined;
};

export const ProjectRetrieve$zodSchema: z.ZodType<ProjectRetrieve> = z.object({
  edge_v2_migration_status: EdgeV2MigrationStatusEnum$zodSchema.optional(),
  enable_dynamo_db: z.boolean().optional(),
  enable_realtime_updates: z.boolean().optional(),
  feature_name_regex: z.string().nullable().optional(),
  hide_disabled_flags: z.boolean().optional(),
  id: z.int().optional(),
  max_features_allowed: z.int().optional(),
  max_segment_overrides_allowed: z.int().optional(),
  max_segments_allowed: z.int().optional(),
  migration_status: z.string().optional(),
  minimum_change_request_approvals: z.int().nullable().optional(),
  name: z.string(),
  only_allow_lower_case_feature_names: z.boolean().optional(),
  organisation: z.int(),
  prevent_flag_defaults: z.boolean().optional(),
  show_edge_identity_overrides_for_feature: z.boolean().optional(),
  stale_flags_limit_days: z.int().optional(),
  total_features: z.int().optional(),
  total_segments: z.int().optional(),
  use_edge_identities: z.boolean().optional(),
  uuid: z.string().optional(),
});
