/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ReleasePipelineInput = {
  name: string;
  description?: string | null | undefined;
  published_at?: string | null | undefined;
  published_by?: number | null | undefined;
};

export const ReleasePipelineInput$zodSchema: z.ZodType<ReleasePipelineInput> = z
  .object({
    description: z.string().nullable().optional(),
    name: z.string(),
    published_at: z.iso.datetime({ offset: true }).nullable().optional(),
    published_by: z.int().nullable().optional(),
  });
