/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PipelineStage, PipelineStage$zodSchema } from "./pipelinestage.js";

/**
 * Adds nested create feature
 */
export type ReleasePipelineDetail = {
  id?: number | undefined;
  name: string;
  project?: number | undefined;
  description?: string | null | undefined;
  stages_count?: number | undefined;
  published_at?: string | null | undefined;
  published_by?: number | null | undefined;
  features?: Array<number> | undefined;
  stages: Array<PipelineStage>;
  completed_features?: string | undefined;
};

export const ReleasePipelineDetail$zodSchema: z.ZodType<ReleasePipelineDetail> =
  z.object({
    completed_features: z.string().optional(),
    description: z.string().nullable().optional(),
    features: z.array(z.int()).optional(),
    id: z.int().optional(),
    name: z.string(),
    project: z.int().optional(),
    published_at: z.iso.datetime({ offset: true }).nullable().optional(),
    published_by: z.int().nullable().optional(),
    stages: z.array(PipelineStage$zodSchema),
    stages_count: z.int().optional(),
  }).describe("Adds nested create feature");
