/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ReleasePipeline = {
  id?: number | undefined;
  name: string;
  project?: number | undefined;
  description?: string | null | undefined;
  stages_count?: number | undefined;
  published_at?: string | null | undefined;
  published_by?: number | null | undefined;
  features?: Array<number> | undefined;
};

export const ReleasePipeline$zodSchema: z.ZodType<ReleasePipeline> = z.object({
  description: z.string().nullable().optional(),
  features: z.array(z.int()).optional(),
  id: z.int().optional(),
  name: z.string(),
  project: z.int().optional(),
  published_at: z.iso.datetime({ offset: true }).nullable().optional(),
  published_by: z.int().nullable().optional(),
  stages_count: z.int().optional(),
});
