/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Role = {
  id?: number | undefined;
  name: string;
  description?: string | null | undefined;
  organisation?: number | undefined;
  tags?: Array<number> | undefined;
};

export const Role$zodSchema: z.ZodType<Role> = z.object({
  description: z.string().nullable().optional(),
  id: z.int().optional(),
  name: z.string(),
  organisation: z.int().optional(),
  tags: z.array(z.int()).optional(),
});
