/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `ADMIN` - Admin
 *
 * @remarks
 * * `USER` - User
 */
export const RoleEnum = {
  Admin: "ADMIN",
  User: "USER",
} as const;
/**
 * * `ADMIN` - Admin
 *
 * @remarks
 * * `USER` - User
 */
export type RoleEnum = ClosedEnum<typeof RoleEnum>;

export const RoleEnum$zodSchema = z.enum([
  "ADMIN",
  "USER",
]).describe("* `ADMIN` - Admin\n* `USER` - User");
