/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = { TOKEN_AUTH: string };

export const Security$zodSchema: z.ZodType<Security> = z.object({
  TOKEN_AUTH: z.string().describe(
    "Organisation API Key. Format: Api-Key <key>",
  ),
});
