/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Metadata, Metadata$zodSchema } from "./metadata.js";
import {
  SegmentRuleOutput,
  SegmentRuleOutput$zodSchema,
} from "./segmentruleoutput.js";

/**
 * Functionality for serializers that need to handle metadata
 */
export type SegmentOutput = {
  id?: number | undefined;
  uuid?: string | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  name: string;
  description?: string | null | undefined;
  project: number;
  feature?: number | null | undefined;
  version_of?: number | null | undefined;
  rules: Array<SegmentRuleOutput>;
  metadata?: Array<Metadata> | undefined;
};

export const SegmentOutput$zodSchema: z.ZodType<SegmentOutput> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  description: z.string().nullable().optional(),
  feature: z.int().nullable().optional(),
  id: z.int().optional(),
  metadata: z.array(Metadata$zodSchema).optional(),
  name: z.string(),
  project: z.int(),
  rules: z.array(SegmentRuleOutput$zodSchema),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
  uuid: z.string().optional(),
  version_of: z.int().nullable().optional(),
}).describe("Functionality for serializers that need to handle metadata");
