/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { MetadataInput, MetadataInput$zodSchema } from "./metadatainput.js";
import {
  SegmentRuleInput,
  SegmentRuleInput$zodSchema,
} from "./segmentruleinput.js";

/**
 * Functionality for serializers that need to handle metadata
 */
export type SegmentInput = {
  name: string;
  description?: string | null | undefined;
  project: number;
  feature?: number | null | undefined;
  version_of?: number | null | undefined;
  rules: Array<SegmentRuleInput>;
  metadata?: Array<MetadataInput> | undefined;
};

export const SegmentInput$zodSchema: z.ZodType<SegmentInput> = z.object({
  description: z.string().nullable().optional(),
  feature: z.int().nullable().optional(),
  metadata: z.array(MetadataInput$zodSchema).optional(),
  name: z.string(),
  project: z.int(),
  rules: z.array(SegmentRuleInput$zodSchema),
  version_of: z.int().nullable().optional(),
}).describe("Functionality for serializers that need to handle metadata");
