/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ConditionInput, ConditionInput$zodSchema } from "./conditioninput.js";
import {
  NestedSegmentRuleInput,
  NestedSegmentRuleInput$zodSchema,
} from "./nestedsegmentruleinput.js";
import {
  SegmentRuleTypeEnum,
  SegmentRuleTypeEnum$zodSchema,
} from "./segmentruletypeenum.js";

/**
 * Adds nested create feature
 */
export type SegmentRuleInput = {
  type: SegmentRuleTypeEnum;
  rules?: Array<NestedSegmentRuleInput> | undefined;
  conditions?: Array<ConditionInput> | undefined;
  delete?: boolean | undefined;
};

export const SegmentRuleInput$zodSchema: z.ZodType<SegmentRuleInput> = z.object(
  {
    conditions: z.array(ConditionInput$zodSchema).optional(),
    delete: z.boolean().optional(),
    rules: z.array(NestedSegmentRuleInput$zodSchema).optional(),
    type: SegmentRuleTypeEnum$zodSchema,
  },
).describe("Adds nested create feature");
