/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConditionOutput,
  ConditionOutput$zodSchema,
} from "./conditionoutput.js";
import {
  NestedSegmentRuleOutput,
  NestedSegmentRuleOutput$zodSchema,
} from "./nestedsegmentruleoutput.js";
import {
  SegmentRuleTypeEnum,
  SegmentRuleTypeEnum$zodSchema,
} from "./segmentruletypeenum.js";

/**
 * Adds nested create feature
 */
export type SegmentRuleOutput = {
  id?: number | undefined;
  type: SegmentRuleTypeEnum;
  rules?: Array<NestedSegmentRuleOutput> | undefined;
  conditions?: Array<ConditionOutput> | undefined;
};

export const SegmentRuleOutput$zodSchema: z.ZodType<SegmentRuleOutput> = z
  .object({
    conditions: z.array(ConditionOutput$zodSchema).optional(),
    id: z.int().optional(),
    rules: z.array(NestedSegmentRuleOutput$zodSchema).optional(),
    type: SegmentRuleTypeEnum$zodSchema,
  }).describe("Adds nested create feature");
