/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `ALL` - all
 *
 * @remarks
 * * `ANY` - any
 * * `NONE` - none
 */
export const SegmentRuleTypeEnum = {
  All: "ALL",
  Any: "ANY",
  None: "NONE",
} as const;
/**
 * * `ALL` - all
 *
 * @remarks
 * * `ANY` - any
 * * `NONE` - none
 */
export type SegmentRuleTypeEnum = ClosedEnum<typeof SegmentRuleTypeEnum>;

export const SegmentRuleTypeEnum$zodSchema = z.enum([
  "ALL",
  "ANY",
  "NONE",
]).describe("* `ALL` - all\n* `ANY` - any\n* `NONE` - none");
