/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TriggerTypeEnum,
  TriggerTypeEnum$zodSchema,
} from "./triggertypeenum.js";

export type StageTrigger = {
  id?: number | undefined;
  trigger_type?: TriggerTypeEnum | undefined;
  trigger_body?: any | null | undefined;
};

export const StageTrigger$zodSchema: z.ZodType<StageTrigger> = z.object({
  id: z.int().optional(),
  trigger_body: z.any().nullable().optional(),
  trigger_type: TriggerTypeEnum$zodSchema.optional(),
});
