/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ActionTypeEnum, ActionTypeEnum$zodSchema } from "./actiontypeenum.js";

export type StageAction = {
  id?: number | undefined;
  action_type?: ActionTypeEnum | undefined;
  action_body?: any | null | undefined;
};

export const StageAction$zodSchema: z.ZodType<StageAction> = z.object({
  action_body: z.any().nullable().optional(),
  action_type: ActionTypeEnum$zodSchema.optional(),
  id: z.int().optional(),
});
