/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BillingStatusEnum,
  BillingStatusEnum$zodSchema,
} from "./billingstatusenum.js";
import { BlankEnum, BlankEnum$zodSchema } from "./blankenum.js";
import {
  PaymentMethodEnum,
  PaymentMethodEnum$zodSchema,
} from "./paymentmethodenum.js";

export type BillingStatus = BillingStatusEnum | BlankEnum;

export const BillingStatus$zodSchema: z.ZodType<BillingStatus> = z.union([
  BillingStatusEnum$zodSchema,
  BlankEnum$zodSchema,
]);

export type PaymentMethod = PaymentMethodEnum | BlankEnum;

export const PaymentMethod$zodSchema: z.ZodType<PaymentMethod> = z.union([
  PaymentMethodEnum$zodSchema,
  BlankEnum$zodSchema,
]);

export type Subscription = {
  id?: number | undefined;
  has_active_billing_periods?: boolean | undefined;
  deleted_at?: string | null | undefined;
  uuid?: string | undefined;
  subscription_id?: string | null | undefined;
  subscription_date?: string | null | undefined;
  plan?: string | null | undefined;
  max_seats?: number | undefined;
  max_api_calls?: number | undefined;
  cancellation_date?: string | null | undefined;
  customer_id?: string | null | undefined;
  billing_status?: BillingStatusEnum | BlankEnum | null | undefined;
  payment_method?: PaymentMethodEnum | BlankEnum | null | undefined;
  notes?: string | null | undefined;
};

export const Subscription$zodSchema: z.ZodType<Subscription> = z.object({
  billing_status: z.union([
    BillingStatusEnum$zodSchema,
    BlankEnum$zodSchema,
  ]).nullable().optional(),
  cancellation_date: z.iso.datetime({ offset: true }).nullable().optional(),
  customer_id: z.string().nullable().optional(),
  deleted_at: z.iso.datetime({ offset: true }).nullable().optional(),
  has_active_billing_periods: z.boolean().optional(),
  id: z.int().optional(),
  max_api_calls: z.int().optional(),
  max_seats: z.int().optional(),
  notes: z.string().nullable().optional(),
  payment_method: z.union([
    PaymentMethodEnum$zodSchema,
    BlankEnum$zodSchema,
  ]).nullable().optional(),
  plan: z.string().nullable().optional(),
  subscription_date: z.iso.datetime({ offset: true }).nullable().optional(),
  subscription_id: z.string().nullable().optional(),
  uuid: z.string().optional(),
});
