/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `ON_ENTER` - Trigger when flag enters stage
 *
 * @remarks
 * * `WAIT_FOR` - Trigger after waiting for x amount of time
 */
export const TriggerTypeEnum = {
  OnEnter: "ON_ENTER",
  WaitFor: "WAIT_FOR",
} as const;
/**
 * * `ON_ENTER` - Trigger when flag enters stage
 *
 * @remarks
 * * `WAIT_FOR` - Trigger after waiting for x amount of time
 */
export type TriggerTypeEnum = ClosedEnum<typeof TriggerTypeEnum>;

export const TriggerTypeEnum$zodSchema = z.enum([
  "ON_ENTER",
  "WAIT_FOR",
]).describe(
  "* `ON_ENTER` - Trigger when flag enters stage\n* `WAIT_FOR` - Trigger after waiting for x amount of time",
);
