/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `int` - Integer
 *
 * @remarks
 * * `unicode` - String
 * * `bool` - Boolean
 */
export const Type975Enum = {
  Int: "int",
  Unicode: "unicode",
  Bool: "bool",
} as const;
/**
 * * `int` - Integer
 *
 * @remarks
 * * `unicode` - String
 * * `bool` - Boolean
 */
export type Type975Enum = ClosedEnum<typeof Type975Enum>;

export const Type975Enum$zodSchema = z.enum([
  "int",
  "unicode",
  "bool",
]).describe("* `int` - Integer\n* `unicode` - String\n* `bool` - Boolean");
