/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { MetadataInput, MetadataInput$zodSchema } from "./metadatainput.js";
import {
  NestedMultivariateFeatureOptionInput,
  NestedMultivariateFeatureOptionInput$zodSchema,
} from "./nestedmultivariatefeatureoption.js";

/**
 * prevent users from changing certain values after creation
 */
export type UpdateFeatureInput = {
  description?: string | null | undefined;
  tags?: Array<number> | undefined;
  multivariate_options?:
    | Array<NestedMultivariateFeatureOptionInput>
    | undefined;
  is_archived?: boolean | undefined;
  is_server_key_only?: boolean | undefined;
  metadata?: Array<MetadataInput> | undefined;
};

export const UpdateFeatureInput$zodSchema: z.ZodType<UpdateFeatureInput> = z
  .object({
    description: z.string().nullable().optional(),
    is_archived: z.boolean().optional(),
    is_server_key_only: z.boolean().optional(),
    metadata: z.array(MetadataInput$zodSchema).optional(),
    multivariate_options: z.array(
      NestedMultivariateFeatureOptionInput$zodSchema,
    ).optional(),
    tags: z.array(z.int()).optional(),
  }).describe("prevent users from changing certain values after creation");
