/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UserList = {
  id?: number | undefined;
  email: string;
  first_name: string;
  last_name: string;
  last_login?: string | null | undefined;
  uuid?: string | undefined;
};

export const UserList$zodSchema: z.ZodType<UserList> = z.object({
  email: z.string(),
  first_name: z.string(),
  id: z.int().optional(),
  last_login: z.iso.datetime({ offset: true }).nullable().optional(),
  last_name: z.string(),
  uuid: z.string().optional(),
});
