/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UserPermissionGroupSummary = {
  id?: number | undefined;
  name?: string | undefined;
};

export const UserPermissionGroupSummary$zodSchema: z.ZodType<
  UserPermissionGroupSummary
> = z.object({
  id: z.int().optional(),
  name: z.string().optional(),
});
