/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `github` - GitHub
 */
export const VcsProviderEnum = {
  Github: "github",
} as const;
/**
 * * `github` - GitHub
 */
export type VcsProviderEnum = ClosedEnum<typeof VcsProviderEnum>;

export const VcsProviderEnum$zodSchema = z.enum([
  "github",
]).describe("* `github` - GitHub");
