/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Adds nested create feature
 */
export type VersionChangeSet = {
  id?: number | undefined;
  feature: number;
  live_from?: string | null | undefined;
  feature_states_to_update: Array<any>;
  feature_states_to_create: Array<any>;
  segment_ids_to_delete_overrides: Array<number>;
};

export const VersionChangeSet$zodSchema: z.ZodType<VersionChangeSet> = z.object(
  {
    feature: z.int(),
    feature_states_to_create: z.array(z.any()),
    feature_states_to_update: z.array(z.any()),
    id: z.int().optional(),
    live_from: z.iso.datetime({ offset: true }).nullable().optional(),
    segment_ids_to_delete_overrides: z.array(z.int()),
  },
).describe("Adds nested create feature");
