/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WorkflowsError = { message: string };

export const WorkflowsError$zodSchema: z.ZodType<WorkflowsError> = z.object({
  message: z.string(),
});
